// Op pad met Serge op Wildeburg 2026 — data
// Omschrijvingen komen letterlijk uit de notitie van Serge.
// desc: null = nog geen notitie geschreven (vul aan in dit bestand!)
// Slots: day = "vr" | "za" | "zo" (festivaldag). Tijden vóór 12:00 horen bij de
// nacht/ochtend NA die festivaldag (bv. day:"vr", start:"02:00" = zaterdagnacht 02:00).
// tip: true = duidelijk enthousiaste notitie (ster in de app).
// live: true = liveset/band. type: "muziek" | "theater" | "host" | "overig"

const WILDEBURG_DATA = {
  festival: "Wildeburg 2026",
  editie: "10–12 juli 2026, Kraggenburg",
  days: [
    { id: "vr", label: "Vrijdag", datum: "10 juli" },
    { id: "za", label: "Zaterdag", datum: "11 juli" },
    { id: "zo", label: "Zondag", datum: "12 juli" }
  ],
  stages: [
    "Wildlive", "Strand", "Helling", "BUD X Lodge", "Bamboebos",
    "Duinpan", "Studio De Baan", "Achtertuin", "Kas"
  ],
  artists: [
    // ===== VRIJDAG overdag =====
    { id: "coloray", name: "Coloray", type: "muziek", genres: ["live", "new wave", "synths"], tip: false,
      desc: "live new wave met veel synths, heeft een ontzettende emo plaat met Gerd Janson gemaakt. Zijn dj sets zijn all over the place.",
      slots: [{ day: "vr", stage: "Wildlive", start: "15:00", end: "16:00", live: true }] },
    { id: "de-nachtwacht", name: "De Nachtwacht", type: "theater", genres: ["theater"], tip: false,
      desc: "een afscheidsrave als theatervoorstelling",
      slots: [{ day: "vr", stage: "Wildlive", start: "17:00", end: "18:00" }] },
    { id: "ploegendienst", name: "Ploegendienst", type: "muziek", genres: ["punk", "live"], tip: true,
      desc: "boze zwarte mannen punk van Nederlandse bodem. Ik ben fan sinds ik Surinaamse broodjes hoorde.",
      slots: [{ day: "vr", stage: "Wildlive", start: "19:00", end: "20:00" }] },
    { id: "s10", name: "S10", type: "muziek", genres: ["nederpop", "live"], tip: false,
      desc: "groot geworden in Nederland met haar alternatieve pop, voor wie van pop houdt",
      slots: [{ day: "vr", stage: "Wildlive", start: "21:00", end: "22:00", live: true }] },
    { id: "raffie-de-driver-xxl", name: "Raffie De Driver XXL", type: "muziek", genres: ["nederpop"], tip: false,
      desc: "de chauffeur van Goldband. Ik ging stuk toen ik dit hoorde, soort van Frans Bauer met kut teksten. Stap maar in mijn dikke raket, ik heb hem pas nog in de olie gezet!",
      slots: [{ day: "vr", stage: "Wildlive", start: "23:00", end: "00:00" }] },
    { id: "liza-van-den-brink", name: "Liza van den Brink", type: "host", genres: ["host"], tip: false,
      desc: "Host op Wildlive, tussen de optredens door (vrijdag).",
      slots: [{ day: "vr", stage: "Wildlive", start: null, end: null }] },

    { id: "nellzz", name: "Nellzz", type: "muziek", genres: ["afrohouse", "gqom", "bubbling", "rnb"], tip: false,
      desc: "blend van afrohouse en gqom, bubbling en rnb. Te hoog cheeseball gehalte voor mij, want fuck autotune!",
      slots: [{ day: "vr", stage: "Strand", start: "12:00", end: "15:00" }] },
    { id: "yusu-selectors", name: "Yusu Selectors", type: "muziek", genres: [], tip: false, desc: null,
      slots: [{ day: "vr", stage: "Strand", start: "15:00", end: "17:00" }] },
    { id: "yucky", name: "Yucky", type: "muziek", genres: [], tip: false, desc: null,
      slots: [{ day: "vr", stage: "Strand", start: "17:00", end: "19:00" }] },
    { id: "bokoesam-dj-steesko", name: "Bokoesam & DJ Steesko (dancehall set)", type: "muziek", genres: ["dancehall"], tip: false,
      desc: "dancehall!! Billen schudden! Ff leuk denk ik",
      slots: [{ day: "vr", stage: "Strand", start: "19:00", end: "21:00" }] },
    { id: "dj-polo", name: "DJ POLO", type: "muziek", genres: ["bubbling", "tropisch"], tip: false,
      desc: "tropische bubbling met steel drums",
      slots: [{ day: "vr", stage: "Strand", start: "21:00", end: "23:00" }] },
    { id: "lamsi", name: "Lamsi", type: "muziek", genres: ["gqom", "afrobeat"], tip: true,
      desc: "Nederlandse Gqom, afrobeat, billen schudden!",
      slots: [{ day: "vr", stage: "Strand", start: "23:00", end: "01:00" }] },

    { id: "di-after", name: "Di After", type: "muziek", genres: ["house", "90s"], tip: false,
      desc: "90s house, staat duidelijk op de helling",
      slots: [{ day: "vr", stage: "Helling", start: "15:00", end: "18:00" }] },
    { id: "daws", name: "DAWS", type: "muziek", genres: ["house", "eurodance"], tip: false,
      desc: "deze mevrouw uit Melbourne draait veel classic house platen, met high energy euro dance achtige tracks",
      slots: [{ day: "vr", stage: "Helling", start: "18:00", end: "20:30" }] },
    { id: "byron-yeates", name: "Byron Yeates", type: "muziek", genres: ["trance", "queer scene"], tip: true,
      desc: "label baas van radiant records, grote naam in de queer scene, heeft een eigen sound die ik heel chill vind",
      slots: [{ day: "vr", stage: "Helling", start: "20:30", end: "21:30", live: true }] },
    { id: "atrip-lammer", name: "ATRIP & LAMMER", type: "muziek", genres: ["hardhouse", "trance", "eurodance"], tip: false,
      desc: "Atrip vind ik wel tof, lammer vind ik vreselijk, maar als je van hardhouse, trancy, eurodance meuk houdt kom je aan je trekken, alleen mij niet bellen",
      slots: [{ day: "vr", stage: "Helling", start: "21:30", end: "00:30" }] },

    { id: "nerds-with-acid", name: "Nerds With Acid", type: "muziek", genres: ["acid"], tip: false, desc: null,
      slots: [{ day: "vr", stage: "BUD X Lodge", start: "12:00", end: "15:00" }] },
    { id: "gioray", name: "Gioray", type: "muziek", genres: ["live", "techno", "breakbeat", "ambient"], tip: false,
      desc: "liveset met alleen hardware, combinatie van ambient, techno en breakbeat. Ik hoop dat hij z'n ambient thuis in Eindhoven laat.",
      slots: [{ day: "vr", stage: "BUD X Lodge", start: "15:00", end: "16:00", live: true }] },
    { id: "jannah", name: "jannah", type: "muziek", genres: ["techno", "electro"], tip: false,
      desc: "techno en electro uit Utrecht, heeft een voorliefde voor wat oudere platen",
      slots: [{ day: "vr", stage: "BUD X Lodge", start: "16:00", end: "18:00" }] },
    { id: "alberta-balsam", name: "Alberta Balsam", type: "muziek", genres: ["electro", "live"], tip: false,
      desc: "stoere chick uit Rotterdam met live set, vuige electronica",
      slots: [{ day: "vr", stage: "BUD X Lodge", start: "18:00", end: "19:00", live: true }] },
    { id: "lazergazer", name: "LazerGazer", type: "muziek", genres: ["electro"], tip: true,
      desc: "Nederlandse/syrische electro chick. Doet denken aan Stingray en Helena Hauff. Boem, tjak!",
      slots: [{ day: "vr", stage: "BUD X Lodge", start: "19:00", end: "21:30" }] },
    { id: "jasmin", name: "Jasmín", type: "muziek", genres: ["breakbeat", "offbeat"], tip: false,
      desc: "offbeat, breakbeat, obscuur, voor de liefhebbers!",
      slots: [{ day: "vr", stage: "BUD X Lodge", start: "21:30", end: "00:00" }] },

    { id: "estrella", name: "ESTRELLA", type: "muziek", genres: ["funk", "vinyl"], tip: true,
      desc: "Amsterdamse vinyl dj, best wel funky en obscuur!",
      slots: [{ day: "vr", stage: "Bamboebos", start: "14:00", end: "17:00" }] },
    { id: "malin-genie", name: "Malin Genie", type: "muziek", genres: ["house"], tip: true,
      desc: "house producer, maakt wel vette platen, net eentje in m'n mandje geklikt!",
      slots: [{ day: "vr", stage: "Bamboebos", start: "17:00", end: "19:30" }] },
    { id: "ogazon", name: "Ogazón", type: "muziek", genres: ["house", "funk", "vinyl"], tip: true,
      desc: "deze mevrouw uit Luxemburg draait errug lekker! Relaxed maar funky. Ik zie haar regelmatig met vinyl draaien.",
      slots: [{ day: "vr", stage: "Bamboebos", start: "19:30", end: "22:00" }] },
    { id: "katia-curie", name: "Katia Curie", type: "muziek", genres: ["house", "funk"], tip: true,
      desc: "deze mevrouw uit Kyiv draait best wel gezellig! Funky house, groovy",
      slots: [{ day: "vr", stage: "Bamboebos", start: "22:00", end: "00:30" }] },

    { id: "bebe-bad", name: "bebe bad", type: "muziek", genres: ["bass", "bubbling"], tip: true,
      desc: "bass heavy, bubbling mevrouw, tof!",
      slots: [{ day: "vr", stage: "Duinpan", start: "13:00", end: "16:00" }] },
    { id: "re-ni", name: "re:ni", type: "muziek", genres: ["breaks", "bass"], tip: false,
      desc: "breaks, bass, het bpm vliegt alle kanten op bij deze vrouw uit Londen. Ik vind het wel wel tof maar vraagt veel van de luisteraar",
      slots: [{ day: "vr", stage: "Duinpan", start: "16:00", end: "18:30" }] },
    { id: "roni", name: "RONI", type: "muziek", genres: ["techno", "uk garage", "latin"], tip: true,
      desc: "techno met veel latin ritme invloeden en uk garage, beetje hardhouse. Bijzondere combi, deze vrouw draait wel lekker door!",
      slots: [{ day: "vr", stage: "Duinpan", start: "18:30", end: "20:30" }] },
    { id: "twiena", name: "TWIENA", type: "muziek", genres: ["techno", "bass"], tip: true,
      desc: "resident bij Raum, de basis is techno maar mixed daar Aziatische en zuid Amerikaanse elementen door heen met veel bass heavy platen. Ik ga kijken!",
      slots: [{ day: "vr", stage: "Duinpan", start: "20:30", end: "22:30" }] },
    { id: "ogazon-rene-wise", name: "Ogazón & Rene Wise", type: "muziek", genres: ["techno"], tip: false,
      desc: "snap deze combi niet want Rene draait wel heel iets anders: duistere zware techno, weinig groove. Niet mijn ding.",
      slots: [{ day: "vr", stage: "Duinpan", start: "22:30", end: "01:30" }] },

    { id: "yuval-avital", name: "Yuval Avital", type: "muziek", genres: [], tip: false, desc: null,
      slots: [{ day: "vr", stage: "Achtertuin", start: "14:00", end: "17:00" }] },
    { id: "kirollus", name: "Kirollus", type: "muziek", genres: ["disco", "vinyl"], tip: false,
      desc: "disco, disco en disco. Op vinyl.",
      slots: [{ day: "vr", stage: "Achtertuin", start: "17:00", end: "20:00" }] },
    { id: "ajuma", name: "Ajuma", type: "muziek", genres: ["disco", "afrobeat"], tip: true,
      desc: "vrolijk, disco, afrikaanse invloeden 'Ariana-muziek'",
      slots: [{ day: "vr", stage: "Achtertuin", start: "20:00", end: "22:00" }] },
    { id: "bradley-zero", name: "Bradley Zero", type: "muziek", genres: ["house", "disco", "eclectic"], tip: true,
      desc: "housy, disco, mag je wel eclectic noemen, vind ik leuk!",
      slots: [{ day: "vr", stage: "Achtertuin", start: "22:00", end: "00:00" }] },

    // Studio De Baan — vrijdag
    { id: "nk-inkomen", name: "NK Inkomen", type: "theater", genres: ["theater"], tip: false, desc: null,
      slots: [{ day: "vr", stage: "Studio De Baan", start: null, end: null }] },
    { id: "hutjedutje-de-bingo", name: "Hutjedutje: De Bingo", type: "overig", genres: ["hutje"], tip: false, desc: null,
      slots: [{ day: "vr", stage: "Studio De Baan", start: null, end: null }] },
    { id: "lezard", name: "Lézard", type: "muziek", genres: ["postpunk", "electroclash", "live"], tip: false,
      desc: "Belgische band. Mix van Postpunk en electroclash. Doet denken aan lcd soundsystem. Maar dan met gitaar solo's.",
      slots: [{ day: "vr", stage: "Studio De Baan", start: "16:00", end: "17:00", live: true }] },
    { id: "hutjegrutje-perspectief", name: "Hutjegrutje: Perspectief", type: "overig", genres: ["hutje"], tip: false, desc: null,
      slots: [{ day: "vr", stage: "Studio De Baan", start: null, end: null }] },
    { id: "zeldzame", name: "Zeldzame", type: "muziek", genres: [], tip: false, desc: null,
      slots: [{ day: "vr", stage: "Studio De Baan", start: "18:00", end: "18:30" }] },
    { id: "ida", name: "IDA", type: "muziek", genres: ["hyperpop"], tip: false,
      desc: "Nederlandse pop mevrouw. Ze noemen dit hyper pop. Niet voor mij. Lijkt erg op alle andere peoples uit deze genre",
      slots: [{ day: "vr", stage: "Studio De Baan", start: "19:30", end: "20:15" }] },
    { id: "hutjeslutje-chaos", name: "Hutjeslutje: Chaos", type: "overig", genres: ["hutje"], tip: false, desc: null,
      slots: [{ day: "vr", stage: "Studio De Baan", start: null, end: null }] },
    { id: "rijck", name: "Rijck", type: "muziek", genres: ["nederhop"], tip: false,
      desc: "de zoveelste Nederlandse autotune rapper, niet om aan te horen",
      slots: [{ day: "vr", stage: "Studio De Baan", start: "20:45", end: "21:15" }] },
    { id: "hutjeklutje-op-elkaar", name: "Hutjeklutje: Op Elkaar", type: "overig", genres: ["hutje"], tip: false, desc: null,
      slots: [{ day: "vr", stage: "Studio De Baan", start: null, end: null }] },
    { id: "tukan", name: "TUKAN", type: "muziek", genres: ["post rock", "jazzy", "live"], tip: false,
      desc: "jazzy post rock band, maar dan elektronisch. Beetje dromerig en duister.",
      slots: [{ day: "vr", stage: "Studio De Baan", start: "22:00", end: "23:00" }] },
    { id: "hutjemutje-vr", name: "Hutjemutje: DJ Olivier, Hutjeflutje Geluidssysteem en Karbonkel & De Smurfen", type: "muziek", genres: ["hutje"], tip: false, desc: null,
      slots: [{ day: "vr", stage: "Studio De Baan", start: "23:00", end: "03:00" }] },

    { id: "de-spot", name: "DE SPOT", type: "overig", genres: ["kunst"], tip: false,
      desc: "Installatie/kunstwerk in de Kas, alle dagen te bezoeken.",
      slots: [
        { day: "vr", stage: "Kas", start: null, end: null },
        { day: "za", stage: "Kas", start: null, end: null },
        { day: "zo", stage: "Kas", start: null, end: null }
      ] },

    // ===== VRIJDAGNACHT (vr → za) =====
    { id: "riria", name: "riria", type: "muziek", genres: ["uk garage", "mashup", "bass"], tip: false,
      desc: "draait veel mash ups van commerciële hits, uk garage en andere bass heavy genres",
      slots: [{ day: "vr", stage: "Strand", start: "01:00", end: "03:00" }] },
    { id: "eycee-passion-deez", name: "EYCEE & Passion DEEZ", type: "muziek", genres: ["uk garage", "2-step", "breakbeat"], tip: false,
      desc: "uk garage, 2 step, breakbeats, gemixed met wat mierzoete vocals",
      slots: [{ day: "vr", stage: "Strand", start: "03:00", end: "05:00" }] },
    { id: "vtss", name: "VTSS", type: "muziek", genres: ["techno"], tip: false, desc: null,
      slots: [{ day: "vr", stage: "Helling", start: "00:30", end: "02:30" }] },
    { id: "thelma", name: "THELMA", type: "muziek", genres: ["electro", "breaks", "techno"], tip: true,
      desc: "combineert electro, breaks en techno. Met een verse dikke release op ATW records. Ik ga hier heel goed op!",
      slots: [{ day: "vr", stage: "Helling", start: "02:30", end: "05:00" }] },
    { id: "newtone", name: "Newtone", type: "muziek", genres: [], tip: false, desc: null,
      slots: [{ day: "vr", stage: "Helling", start: "05:00", end: "08:00" }] },
    { id: "gyrofield", name: "gyrofield", type: "muziek", genres: ["drum n bass"], tip: false,
      desc: "drum n bass van een Amsterdamse queer mevrouw. Ik vind haar tracks tof maar haar setjes een beetje moeilijk.",
      slots: [{ day: "vr", stage: "BUD X Lodge", start: "00:00", end: "02:00" }] },
    { id: "sully", name: "Sully", type: "muziek", genres: ["2-step", "jungle", "uk garage"], tip: true,
      desc: "underground 2step, jungle en UKG, produceert hele dikke platen!",
      slots: [{ day: "vr", stage: "BUD X Lodge", start: "02:00", end: "04:00" }] },
    { id: "dirtydms", name: "Dirtydms", type: "muziek", genres: ["dub", "dubstep", "drum n bass", "jungle"], tip: true,
      desc: "uit Rotterdam, van dub naar dubstep en drum n bass en jungle, alles duister. Niet de makkelijkste set maar ik vind het wel vet!",
      slots: [{ day: "vr", stage: "BUD X Lodge", start: "04:00", end: "06:00" }] },
    { id: "dj-sweet6teen", name: "dj sweet6teen", type: "muziek", genres: ["house"], tip: false,
      desc: "house, laidback. Haar RA mix is wel nice maar de rest een beetje saai",
      slots: [{ day: "vr", stage: "Bamboebos", start: "00:30", end: "03:00" }] },
    { id: "priori", name: "Priori", type: "muziek", genres: ["techno", "idm"], tip: false,
      desc: "goed wazige techno/idm uit Canada, voor de late uurtjes als je er toch al niets meer van begrijpt",
      slots: [{ day: "vr", stage: "Bamboebos", start: "03:00", end: "06:00" }] },
    { id: "blawan", name: "Blawan", type: "muziek", genres: ["techno", "offbeat"], tip: false,
      desc: "vaak offbeat, weirde sounds, heeft zeker vette tracks maar ik vind hem vooral eigenlijk veel moeilijk doen, geen fan",
      slots: [{ day: "vr", stage: "Duinpan", start: "01:30", end: "03:30" }] },
    { id: "rosati", name: "Rosati", type: "muziek", genres: ["techno", "90s", "vinyl"], tip: true,
      desc: "draait techno met die echte 90s, beetje hardgroove sound op vinyl. Ik ben fan!",
      slots: [{ day: "vr", stage: "Duinpan", start: "03:30", end: "06:00" }] },
    { id: "danilo-plessow", name: "Danilo Plessow", type: "muziek", genres: ["disco", "soul", "funk"], tip: false,
      desc: "ook wel bekend als Motorcity drum ensemble. Bekend van z'n dikke raw cuts platen. Disco, soul, funky, lekker ontspannen.",
      slots: [{ day: "vr", stage: "Achtertuin", start: "00:00", end: "02:30" }] },
    { id: "vasco", name: "Vasco", type: "muziek", genres: [], tip: false, desc: null,
      slots: [{ day: "vr", stage: "Achtertuin", start: "02:30", end: "05:00" }] },
    { id: "ame", name: "Âme", type: "muziek", genres: ["house", "synths"], tip: false,
      desc: "oftwel Frank Wiedemann, veel synths, te traag voor mij, weinig groove",
      slots: [{ day: "vr", stage: "Kas", start: "00:00", end: "05:00" }] },
    { id: "optimo", name: "Ochtendgloren: Optimo (Espacio)", type: "muziek", genres: ["eclectic", "new wave", "disco", "ochtendgloren"], tip: false,
      desc: "de helft van de bekende optimo, want de andere is er niet meer 😔. Zijn sets gaan alle kanten op. Van New Wave naar disco en cumbia en electro. Voor de liefhebbers.",
      slots: [{ day: "vr", stage: "Studio De Baan", start: "06:00", end: "12:00" }] },

    // ===== ZATERDAG overdag =====
    { id: "stay-away-from-dante", name: "stay away from dante!", type: "muziek", genres: [], tip: false, desc: null,
      slots: [{ day: "za", stage: "Wildlive", start: "13:00", end: "13:45" }] },
    { id: "de-baron", name: "De Baron", type: "muziek", genres: ["live", "theatraal"], tip: true,
      desc: "7 koppige band met blazers, lekker theatraal, zingen graag in het Duits. Ik vind het tof!!!",
      slots: [{ day: "za", stage: "Wildlive", start: "15:00", end: "16:00", live: true }] },
    { id: "nana-benz-du-togo", name: "Nana Benz Du Togo", type: "muziek", genres: ["live", "ritmisch"], tip: false,
      desc: "5 koppige band uit Togo. Klinkt gezellig! Heeft blijkbaar iets met voodoo te maken 😬. Ritmisch met een en beetje wazige synth lijntjes",
      slots: [{ day: "za", stage: "Wildlive", start: "17:00", end: "18:00", live: true }] },
    { id: "yung-felix-presents", name: "Yung Felix presents...", type: "muziek", genres: ["hiphop"], tip: false, desc: null,
      slots: [{ day: "za", stage: "Wildlive", start: "19:00", end: "20:00" }] },
    { id: "hang-youth", name: "Hang Youth", type: "muziek", genres: ["punk", "live"], tip: true,
      desc: "Amsterdamse protest punk, verwacht 50 nummers in een half uur, leg de zuidas in de as!",
      slots: [{ day: "za", stage: "Wildlive", start: "21:00", end: "22:00", live: true }] },
    { id: "jersey", name: "Jersey", type: "muziek", genres: ["drum n bass", "pop"], tip: false,
      desc: "poppy, drum n bass, mierzoet. Ik kan hier echt helemaal niks mee. Ik kwam eerst uit bij een Nederlandse duo orkest. Daar ging ik wel beter op.",
      slots: [{ day: "za", stage: "Wildlive", start: "23:00", end: "00:00" }] },
    { id: "mylan", name: "Mylan", type: "host", genres: ["host"], tip: false,
      desc: "Host op Wildlive, tussen de optredens door (zaterdag).",
      slots: [{ day: "za", stage: "Wildlive", start: null, end: null }] },

    { id: "ism-schism", name: "Ism Schism Soundsism", type: "muziek", genres: ["dub", "soundsystem"], tip: false,
      desc: "nog meer dub maar nu uit Amersfoort en deze gasten hebben sowieso hun eigen soundsystem mee",
      slots: [{ day: "za", stage: "Strand", start: "12:00", end: "15:00" }] },
    { id: "mr-scruff-mc-kwasi", name: "Mr Scruff & MC Kwasi", type: "muziek", genres: ["eclectic", "hiphop", "disco", "funk"], tip: false,
      desc: "deze oudgediende draait altijd gezellig, hiphop, breaks, disco, funky, obscuur",
      slots: [{ day: "za", stage: "Strand", start: "15:00", end: "19:00" }] },
    { id: "tash-lc", name: "Tash LC", type: "muziek", genres: ["gqom", "afrohouse"], tip: false,
      desc: "gqom/afrohouse dj uit London met een vaste radioshow op NTS radio",
      slots: [{ day: "za", stage: "Strand", start: "19:00", end: "21:00" }] },
    { id: "state-offf", name: "State OFFF", type: "muziek", genres: ["gqom"], tip: false,
      desc: "vanuit zimbabwe via zuid Afrika in Amsterdam beland. Gqom voor de fijnproever.",
      slots: [{ day: "za", stage: "Strand", start: "21:00", end: "23:00" }] },
    { id: "jyoty", name: "Jyoty", type: "muziek", genres: ["rnb", "reggaeton", "mashup"], tip: true,
      desc: "RnB, reggaeton, mash ups, dansen!",
      slots: [{ day: "za", stage: "Strand", start: "23:00", end: "01:00" }] },

    { id: "job-jobse", name: "Job Jobse", type: "muziek", genres: ["trance"], tip: false,
      desc: "voor de liefhebbers van trance en blije handjes in de lucht, 5 uur lang!",
      slots: [{ day: "za", stage: "Helling", start: "15:00", end: "19:00" }] },
    { id: "moxes-phia", name: "Moxes & PHIA", type: "muziek", genres: ["house", "soul"], tip: false,
      desc: "Mozes dit maal zonder z’n vaste maatje Emvae, maar met Phia, de programmeur van Doka, verwacht hier house, vrolijk, soulfull,",
      slots: [{ day: "za", stage: "Helling", start: "19:00", end: "21:30" }] },
    { id: "avalon-emerson", name: "Avalon Emerson", type: "muziek", genres: ["techno", "pop"], tip: false,
      desc: "snap de hype niet, veel te poppy en commercieel (luister naar set Dekmantel 2024)",
      slots: [{ day: "za", stage: "Helling", start: "21:30", end: "00:00" }] },

    { id: "etape", name: "Etape", type: "muziek", genres: ["new wave", "live"], tip: false,
      desc: "als het de band is, is het wel tof. Doet denken aan Depeche Mode. De dj maakt soundscapes en moeten we ver van weg blijven. Het kan ook nog een Amsterdams dj collectief zijn… onduidelijk!",
      slots: [{ day: "za", stage: "BUD X Lodge", start: "12:00", end: "16:00" }] },
    { id: "mammo", name: "Mammo", type: "muziek", genres: ["dub techno", "live", "hypnotic"], tip: false,
      desc: "stripped back (dub) techno, maar dan live, neigt naar hypnotic. Lekker moeilijk!",
      slots: [{ day: "za", stage: "BUD X Lodge", start: "16:00", end: "17:00", live: true }] },
    { id: "herve-xiaolin", name: "Hervé & XIAOLIN", type: "muziek", genres: ["bass", "vinyl"], tip: true,
      desc: "vriend Hervé draait vieze bassy platen oa in de panaroma bar. Vriendin Xiaolin draait ook vinyl, maar wel wat moeilijker. Voor Herve kom ik zeker kijken!",
      slots: [{ day: "za", stage: "BUD X Lodge", start: "17:00", end: "20:00" }] },
    { id: "nthng", name: "nthng", type: "muziek", genres: ["dub techno", "laidback"], tip: false,
      desc: "maakt wat meer laidback dub techno platen, in z’n sets is dub ook de gemene deler. Ideaal om te luisteren onder het genot van een jointje",
      slots: [{ day: "za", stage: "BUD X Lodge", start: "20:00", end: "22:30" }] },
    { id: "torus", name: "Torus", type: "muziek", genres: ["trance", "ambient"], tip: false,
      desc: "trance kunstenaar uit Den Haag die ook ambient maakt",
      slots: [{ day: "za", stage: "BUD X Lodge", start: "22:30", end: "00:30" }] },

    { id: "idilay", name: "Idilay", type: "muziek", genres: ["electro", "breakbeat", "acid"], tip: false,
      desc: "deze mevrouw stond al in Raum, Tillatec en Bret. Gaat van electro naar breakbeat, links af bij acid. Beetje ingewikkeld.",
      slots: [{ day: "za", stage: "Bamboebos", start: "14:00", end: "17:00" }] },
    { id: "mountain-people", name: "Mountain People", type: "muziek", genres: ["house", "minimal", "laidback"], tip: false,
      desc: "niet heel erg veelzeggend, beetje laidback elektronisch",
      slots: [{ day: "za", stage: "Bamboebos", start: "17:00", end: "19:30" }] },
    { id: "plo-man", name: "PLO Man", type: "muziek", genres: ["dub techno", "minimal"], tip: false,
      desc: "dub, minimal en diepe techno. Weinig te vinden over deze persoon maar klinkt wel lekker en een eigen geluid",
      slots: [{ day: "za", stage: "Bamboebos", start: "19:30", end: "22:00" }] },
    { id: "raresh", name: "Raresh", type: "muziek", genres: ["minimal", "house"], tip: false,
      desc: "soort van jonge Villalobos, lekker vaag, ben benieuwd of hij ook van die lange platen draait",
      slots: [{ day: "za", stage: "Bamboebos", start: "22:00", end: "01:00" }] },

    { id: "alec-dienaar", name: "Alec Dienaar", type: "muziek", genres: ["house", "old school"], tip: false,
      desc: "dikke old school house, produceert zelf house bangers",
      slots: [{ day: "za", stage: "Duinpan", start: "13:00", end: "16:00" }] },
    { id: "dj-fuckoff", name: "DJ Fuckoff", type: "muziek", genres: ["electro"], tip: false,
      desc: "het thema is duidelijk; nummers die fuk around, my pussy en I'm a freak heten. Vieze electro met vrouwen die schreeuwen over hun pussy.",
      slots: [{ day: "za", stage: "Duinpan", start: "16:00", end: "18:30" }] },
    { id: "mcr-t", name: "MCR-T", type: "muziek", genres: [], tip: false,
      desc: "rare Joost Kleijn meets prins S en de geit",
      slots: [{ day: "za", stage: "Duinpan", start: "18:30", end: "20:30" }] },
    { id: "u-r-trax", name: "u.r.trax", type: "muziek", genres: ["techno"], tip: false, desc: null,
      slots: [{ day: "za", stage: "Duinpan", start: "20:30", end: "23:00" }] },
    { id: "delano-legito", name: "Delano Legito", type: "muziek", genres: ["techno", "minimal"], tip: false,
      desc: "duistere techno, vrij minimalistisch",
      slots: [{ day: "za", stage: "Duinpan", start: "23:00", end: "01:00" }] },

    // Studio De Baan — zaterdag
    { id: "de-gestampte-meisjes", name: "De Gestampte Meisjes", type: "theater", genres: ["theater"], tip: false,
      desc: "maf theater, vieze meisjes muziek, ik wil alleen maar pony rijden",
      slots: [{ day: "za", stage: "Studio De Baan", start: "14:00", end: "14:45" }] },
    { id: "mok-the-one-man-band", name: "MOK The One Man Band", type: "muziek", genres: ["live"], tip: false, desc: null,
      slots: [{ day: "za", stage: "Studio De Baan", start: null, end: null }] },
    { id: "la-banda-fantastica", name: "La Banda Fantastica", type: "muziek", genres: ["cumbia", "live"], tip: false,
      desc: "Nederlandse Cumbia band. Ik kon er geen muziek van vinden.",
      slots: [{ day: "za", stage: "Studio De Baan", start: "16:00", end: "17:00", live: true }] },
    { id: "wine-ya-waist-workshop", name: "Wine Ya Waist Workshop", type: "overig", genres: ["workshop"], tip: false, desc: null,
      slots: [{ day: "za", stage: "Studio De Baan", start: null, end: null }] },
    { id: "nnelg", name: "Nnelg", type: "muziek", genres: [], tip: false, desc: null,
      slots: [{ day: "za", stage: "Studio De Baan", start: "18:00", end: "18:45" }] },
    { id: "kurashi", name: "Kurashi", type: "muziek", genres: [], tip: false, desc: null,
      slots: [{ day: "za", stage: "Studio De Baan", start: null, end: null }] },
    { id: "alice-olsthoorn", name: "Alice Olsthoorn", type: "muziek", genres: ["hardhouse", "trance"], tip: false,
      desc: "hardhouse, snel, trancy",
      slots: [{ day: "za", stage: "Studio De Baan", start: "20:30", end: "21:00" }] },
    { id: "milan-mes", name: "Milan Mes", type: "overig", genres: [], tip: false, desc: null,
      slots: [{ day: "za", stage: "Studio De Baan", start: null, end: null }] },
    { id: "kaat-van-stralen", name: "Kaat van Stralen", type: "muziek", genres: ["postpunk", "live"], tip: false,
      desc: "Vlaamse postpunk. Voor wie van Belgische schreeuwende vrouwen houdt.",
      slots: [{ day: "za", stage: "Studio De Baan", start: "22:30", end: "23:15", live: true }] },
    { id: "hutjemutje-za", name: "Hutjemutje: Gustaf 3000, TAJ en HELLE", type: "muziek", genres: ["hutje"], tip: false, desc: null,
      slots: [{ day: "za", stage: "Studio De Baan", start: "23:15", end: "03:00" }] },

    { id: "lysah", name: "Lysah", type: "muziek", genres: ["disco", "boogie", "vinyl"], tip: false,
      desc: "obscure disco/boogie vinyl dj uit Nijmegen",
      slots: [{ day: "za", stage: "Achtertuin", start: "14:00", end: "17:00" }] },
    { id: "doppelgang", name: "Doppelgang", type: "muziek", genres: ["house"], tip: true,
      desc: "onze favoriete tweeling! Altijd feest 🥳",
      slots: [{ day: "za", stage: "Achtertuin", start: "17:00", end: "19:30" }] },
    { id: "dj-subaru", name: "DJ Subaru", type: "muziek", genres: ["italo", "electro"], tip: false,
      desc: "obscure Italo en electro",
      slots: [{ day: "za", stage: "Achtertuin", start: "19:30", end: "22:00" }] },
    { id: "sound-metaphors-djs", name: "Sound Metaphors DJs", type: "muziek", genres: ["vinyl"], tip: false,
      desc: "hebben een platenzaak in Berlijn en hadden ook een avond in de panorama bar. Wat ze draaien? Geen idee!",
      slots: [{ day: "za", stage: "Achtertuin", start: "22:00", end: "00:30" }] },

    // ===== ZATERDAGNACHT (za → zo) =====
    { id: "champion", name: "Champion", type: "muziek", genres: ["uk garage"], tip: true,
      desc: "dikke UK Garage, grote naam uit de stal van interplanetary criminal etc, ik sta hier links vooraan, pull up!!!",
      slots: [{ day: "za", stage: "Strand", start: "01:00", end: "02:30" }] },
    { id: "sam-girling", name: "Sam Girling", type: "muziek", genres: ["house", "uk garage"], tip: true,
      desc: "house, UKG, draait wel vet eigenlijk!",
      slots: [{ day: "za", stage: "Strand", start: "02:30", end: "05:00" }] },
    { id: "milion", name: "Milion", type: "muziek", genres: ["uk garage"], tip: false,
      desc: "uk garage uit Nederland, heeft net een klapper uit gebracht op het label van Interplanetary Criminal. Neigt wel regelmatige naar de meer cheesy hoek. Te cheesy voor mij.",
      slots: [{ day: "za", stage: "Helling", start: "00:00", end: "02:30" }] },
    { id: "x-club", name: "X CLUB.", type: "muziek", genres: ["techno", "club"], tip: false, desc: null,
      slots: [{ day: "za", stage: "Helling", start: "02:30", end: "05:00" }] },
    { id: "swim", name: "SWIM", type: "muziek", genres: ["rnb", "alternatief"], tip: false,
      desc: "ofwel someone who isn't me. Alternatieve rnb noemen ze het zelf. Ik vind het maar weeïg. Te slick voor mijn smaak.",
      slots: [{ day: "za", stage: "Helling", start: "05:00", end: "08:00" }] },
    { id: "hysteria-djs", name: "Hysteria DJ's", type: "muziek", genres: ["hardcore", "gabber"], tip: false,
      desc: "early hardcore! Voor de gabbers onder ons",
      slots: [{ day: "za", stage: "BUD X Lodge", start: "00:30", end: "02:00" }] },
    { id: "promo", name: "Promo", type: "muziek", genres: ["hardcore"], tip: true,
      desc: "hardcore legende uit Nederland. Ik luisterde dit vroeger veel en heb nog steeds (of eigenlijk weer) platen van hem. Old school hardcode beukers!",
      slots: [{ day: "za", stage: "BUD X Lodge", start: "02:00", end: "03:30" }] },
    { id: "hyperlili", name: "HyperLili", type: "muziek", genres: ["techno", "trance"], tip: false,
      desc: "trippy, trancy techno, snel. Ik vond ook een hardcore set van haar 😂 als je lekker in je energie zit 's nachts!",
      slots: [{ day: "za", stage: "BUD X Lodge", start: "03:30", end: "06:00" }] },
    { id: "tini", name: "tINI", type: "muziek", genres: ["electro", "house", "techno"], tip: true,
      desc: "badass mevrouw die zich niet aan genres houdt maar wel heel erg lekker draait. Electro, house, beetje techno, alles groovy",
      slots: [{ day: "za", stage: "Bamboebos", start: "01:00", end: "03:30" }] },
    { id: "samuel-deep", name: "Samuel Deep", type: "muziek", genres: ["house"], tip: false,
      desc: "de sheriff van slapfunk, slapfunk house dus!",
      slots: [{ day: "za", stage: "Bamboebos", start: "03:30", end: "06:00" }] },
    { id: "rodhad", name: "RØDHÅD", type: "muziek", genres: ["techno", "dub techno"], tip: false,
      desc: "de bekende techno Viking uit Berlijn, sterk door dub techno beïnvloede stijl, classic duinpan dj",
      slots: [{ day: "za", stage: "Duinpan", start: "01:00", end: "03:30" }] },
    { id: "nadia-struiwigh", name: "Nadia Struiwigh", type: "muziek", genres: ["jungle", "electro", "techno"], tip: false,
      desc: "verwacht hier een mix van jungle, electro en techno. Live neemt ze altijd een berg aan instrumenten mee, maar ik vrees dat dit een dj set wordt..",
      slots: [{ day: "za", stage: "Duinpan", start: "03:30", end: "06:00" }] },
    { id: "erol-alkan", name: "Erol Alkan", type: "muziek", genres: ["electro", "italo", "disco"], tip: false,
      desc: "electro, italo, draait ook wel eens disco",
      slots: [{ day: "za", stage: "Achtertuin", start: "00:30", end: "03:00" }] },
    { id: "i-f", name: "I-F", type: "muziek", genres: ["italo", "electro"], tip: false,
      desc: "oude italo schurk uit Den Haag",
      slots: [{ day: "za", stage: "Achtertuin", start: "03:00", end: "05:00" }] },
    { id: "acid-pauli", name: "Acid Pauli", type: "muziek", genres: ["slow house"], tip: false,
      desc: "slow house, wazige kippen landjuweel vibe",
      slots: [{ day: "za", stage: "Kas", start: "00:00", end: "05:00" }] },
    { id: "benny-rodrigues", name: "Ochtendgloren: Benny Rodrigues", type: "muziek", genres: ["ochtendgloren"], tip: true,
      desc: "Benny doet het ochtendgloren, wekkertje zetten maar!",
      slots: [{ day: "za", stage: "Studio De Baan", start: "06:00", end: "12:00" }] },

    // ===== ZONDAG =====
    { id: "david-august", name: "David August", type: "muziek", genres: ["ambient", "live"], tip: false,
      desc: "oudgediende die een live ambient set doet en een dj set. Geen flauw idee wat ik hier van moet verwachten. Ik vind z'n tracks over het algemeen wat…. Saai",
      slots: [
        { day: "zo", stage: "Wildlive", start: "13:00", end: "14:00", live: true, label: "ambient live" },
        { day: "zo", stage: "BUD X Lodge", start: "21:00", end: "23:00", label: "dj set" }
      ] },
    { id: "quique", name: "QUIQUE", type: "muziek", genres: ["pop", "rnb", "reggaeton"], tip: false,
      desc: "urban pop: combinatie van rnb, reggaeton en hiphop, veel te poppy voor mij",
      slots: [{ day: "zo", stage: "Wildlive", start: "15:00", end: "16:00" }] },
    { id: "kevin", name: "Kevin", type: "muziek", genres: ["nederhop"], tip: false,
      desc: "Nederlandse rapper die het blijkbaar best wel goed doet. Ik ben duidelijk uit de nederhop 😂 autotune, mij niet bellen",
      slots: [{ day: "zo", stage: "Wildlive", start: "17:00", end: "17:45" }] },
    { id: "kog", name: "K.O.G.", type: "muziek", genres: ["afrobeat", "funk", "reggae", "live"], tip: true,
      desc: "mix van afrobeat, funk en reggae. Neemt zo te zien een 8 koppige band mee. Zomers en gezellig!",
      slots: [{ day: "zo", stage: "Wildlive", start: "19:00", end: "20:00", live: true }] },
    { id: "gallowstreet", name: "Gallowstreet", type: "muziek", genres: ["brass", "afrobeat", "funk", "live"], tip: true,
      desc: "Amsterdamse brassband, mix van afrobeat, funk en dance, leuk!!!",
      slots: [{ day: "zo", stage: "Wildlive", start: "21:00", end: "22:00", live: true }] },
    { id: "dj-truus-tune", name: "DJ Truus & Tune", type: "host", genres: ["host"], tip: false,
      desc: "Host op Wildlive, tussen de optredens door (zondag).",
      slots: [{ day: "zo", stage: "Wildlive", start: null, end: null }] },

    { id: "ketama-man", name: "Ketama Man", type: "muziek", genres: ["reggae", "vinyl"], tip: false,
      desc: "vinyl reggae dj die ook mc is, light it up!",
      slots: [{ day: "zo", stage: "Strand", start: "12:00", end: "15:00" }] },
    { id: "iration-steppas", name: "Iration Steppas", type: "muziek", genres: ["dub", "soundsystem"], tip: false,
      desc: "dub met een hoofdletter D. Ik gok dat ze hun eigen soundsystem mee nemen.",
      slots: [{ day: "zo", stage: "Strand", start: "15:00", end: "18:00" }] },
    { id: "dj-spit-miley-serious", name: "DJ Spit & Miley Serious", type: "muziek", genres: ["bubbling", "garage", "jungle"], tip: false,
      desc: "all over the place: bubbling met hiphop invloeden, garage, jungle",
      slots: [{ day: "zo", stage: "Strand", start: "18:00", end: "21:00" }] },
    { id: "hamdi", name: "Hamdi", type: "muziek", genres: ["uk garage", "dubstep", "grime"], tip: true,
      desc: "mix van UKG, Dubstep en grime uit de UK. Jullie vinden mij hier links vooraan.",
      slots: [{ day: "zo", stage: "Strand", start: "21:00", end: "23:00" }] },

    { id: "kinetiks", name: "KINETIKS", type: "muziek", genres: ["house", "club"], tip: false,
      desc: "vrouwelijk dj duo, (club)house, niet heel erg uitgesproken. Doet aan housequake denken.",
      slots: [{ day: "zo", stage: "Helling", start: "14:00", end: "16:00" }] },
    { id: "coffintexts", name: "Coffintexts", type: "muziek", genres: ["bass"], tip: false,
      desc: "Miami based artiest, bass heavy maar wel veel suiker, ik weet het niet!",
      slots: [{ day: "zo", stage: "Helling", start: "16:00", end: "18:00" }] },
    { id: "helena-lauwaert", name: "Helena Lauwaert", type: "muziek", genres: ["hardhouse", "house", "trance"], tip: false,
      desc: "combinatie van hard house, house en een beetje trance uit Gent. Best wel funky eigenlijk!",
      slots: [{ day: "zo", stage: "Helling", start: "18:00", end: "20:00" }] },
    { id: "geheime-act", name: "? (geheime act)", type: "muziek", genres: ["verrassing"], tip: false,
      desc: "Nog geheim! Op het blokkenschema staat hier alleen een vraagteken.",
      slots: [{ day: "zo", stage: "Helling", start: "20:00", end: "23:00" }] },

    { id: "shana", name: "Shana", type: "muziek", genres: ["singer-songwriter"], tip: false,
      desc: "ik denk dat dit een singer songwriter is, maar ik weet het niet zeker 😬 heeft opgetreden met Zuco103",
      slots: [{ day: "zo", stage: "BUD X Lodge", start: "12:00", end: "15:00" }] },
    { id: "milio", name: "Milio", type: "muziek", genres: ["electronica", "laidback"], tip: false,
      desc: "lager tempo, beetje trippy, hele laidback electronica. Ik vind z’n Sisyphos set wel tof",
      slots: [{ day: "zo", stage: "BUD X Lodge", start: "15:00", end: "17:00" }] },
    { id: "360-soundsystem", name: "360 Soundsystem (Patrice Bäumel & Nuno Dos Santos)", type: "muziek", genres: ["house", "techno"], tip: false,
      desc: null,
      slots: [{ day: "zo", stage: "BUD X Lodge", start: "17:00", end: "21:00" }] },

    { id: "dana-kuehr", name: "Dana Kuehr", type: "muziek", genres: ["house", "funk", "ambient"], tip: false,
      desc: "zomers, ontspannen, niet te snel, best wel funky. Zo'n setje voor met een jointje in de middagzon. Kan overigens ook zomaar ineens een ambient set zijn.",
      slots: [{ day: "zo", stage: "Bamboebos", start: "13:00", end: "17:00" }] },
    { id: "dyed-soundorom", name: "Dyed Soundorom", type: "muziek", genres: ["house"], tip: false,
      desc: "obscure house, tempo wat omlaag, beetje moeilijk wel",
      slots: [{ day: "zo", stage: "Bamboebos", start: "17:00", end: "20:00" }] },
    { id: "love-on-the-rocks", name: "Love On The Rocks: PARAMIDA & Simone de Kunovich & Pancratio", type: "muziek", genres: ["house"], tip: false,
      desc: "niet helemaal duidelijk wie of wat dit is maar klinkt als house. Verder heb ik er niet zo veel over te zeggen.",
      slots: [{ day: "zo", stage: "Bamboebos", start: "20:00", end: "23:00" }] },

    { id: "altinbas", name: "Altinbas", type: "muziek", genres: ["techno", "hypnotic"], tip: false,
      desc: "hypnotic techno, duister",
      slots: [{ day: "zo", stage: "Duinpan", start: "13:00", end: "17:30" }] },
    { id: "binh", name: "Binh", type: "muziek", genres: ["acid", "electro"], tip: true,
      desc: "Acid, electro, maffe elektronica, verrassend!",
      slots: [{ day: "zo", stage: "Duinpan", start: "17:30", end: "20:00" }] },
    { id: "kittin-steffi", name: "Kittin & Steffi", type: "muziek", genres: ["electro", "old school"], tip: false,
      desc: "twee old school electro beukers.",
      slots: [{ day: "zo", stage: "Duinpan", start: "20:00", end: "23:00" }] },

    // Studio De Baan — zondag
    { id: "hokjesdenker", name: "Hokjesdenker", type: "theater", genres: ["theater", "absurdisme"], tip: false,
      desc: "theater met twee idiots, gaat eigenlijk nergens over, absurdisme",
      slots: [{ day: "zo", stage: "Studio De Baan", start: "14:00", end: "14:45" }] },
    { id: "hutjemutje-naaicursus", name: "Hutjemutje Naaicursus: Leren Pijpen", type: "overig", genres: ["hutje", "workshop"], tip: false, desc: null,
      slots: [{ day: "zo", stage: "Studio De Baan", start: null, end: null }] },
    { id: "igor", name: "Igor", type: "muziek", genres: ["hiphop", "nederlandstalig"], tip: false,
      desc: "producer, zanger en rapper. Dromerige, lieve, Nederlandstalige hiphop",
      slots: [{ day: "zo", stage: "Studio De Baan", start: "16:00", end: "16:45" }] },
    { id: "hutjeprutje-de-veiling", name: "Hutjeprutje: De Veiling", type: "overig", genres: ["hutje"], tip: false, desc: null,
      slots: [{ day: "zo", stage: "Studio De Baan", start: null, end: null }] },
    { id: "kagami", name: "KAGAMI", type: "muziek", genres: ["disco", "funk", "live"], tip: false,
      desc: "cosmic funk duo uit Rotterdam. Donny Benet maar dan net iets meer gelikt. Zoete en blije disco pop.",
      slots: [{ day: "zo", stage: "Studio De Baan", start: "18:00", end: "19:00", live: true }] },
    { id: "hutjemutje-idols", name: "Hutjemutje: Idols", type: "overig", genres: ["hutje"], tip: false, desc: null,
      slots: [{ day: "zo", stage: "Studio De Baan", start: null, end: null }] },
    { id: "jet-van-der-steen", name: "jet van der steen", type: "muziek", genres: ["pop", "singer-songwriter"], tip: false,
      desc: "singer songwriter, gen Z pop nummers van max 2,5 minuut",
      slots: [{ day: "zo", stage: "Studio De Baan", start: "20:00", end: "20:45", live: true }] },
    { id: "hutje-mutje-zo", name: "HUTJE & MUTJE", type: "muziek", genres: ["hutje"], tip: false, desc: null,
      slots: [
        { day: "zo", stage: "Studio De Baan", start: "20:45", end: "22:00", label: "HUTJE" },
        { day: "zo", stage: "Studio De Baan", start: "22:00", end: "23:00", label: "MUTJE" }
      ] },

    { id: "margaux", name: "Margaux", type: "muziek", genres: ["house", "soul"], tip: false,
      desc: "happy soul full groovy house",
      slots: [{ day: "zo", stage: "Achtertuin", start: "14:00", end: "17:00" }] },
    { id: "juliana-x", name: "Juliana X", type: "muziek", genres: ["techno", "funk"], tip: true,
      desc: "dikke funky techno uit Rotterdam. Beuken!",
      slots: [{ day: "zo", stage: "Achtertuin", start: "17:00", end: "19:00" }] },
    { id: "o-flynn", name: "O'Flynn", type: "muziek", genres: ["house", "uk bass"], tip: true,
      desc: "producer uit de UK op oa Ninja Tune, houdt duidelijk van Afrikaanse invloeden en dromerige synths. Ik vind het wel vet! Past bij liefhebbers van Four Tet, Apparat en Bicep",
      slots: [{ day: "zo", stage: "Achtertuin", start: "19:00", end: "21:00" }] },
    { id: "tonno-disko", name: "Tonno Disko", type: "muziek", genres: ["disco", "funk"], tip: false,
      desc: "noemt zichzelf funk/disco dj, vocalist en wodka lover. Het is vooral een blije kerel die happy de peppie disco draait.",
      slots: [{ day: "zo", stage: "Achtertuin", start: "21:00", end: "23:00" }] },

    // ===== WEL IN DE NOTITIE, (NOG) NIET OP HET BLOKKENSCHEMA =====
    { id: "bevan", name: "Bevan", type: "muziek", genres: ["house", "uk garage"], tip: false,
      desc: "soulvolle house, veel vocals, oude uk garage",
      slots: [] },
    { id: "freddi", name: "Freddi", type: "muziek", genres: ["uk garage", "speed garage", "hardhouse"], tip: false,
      desc: "UK garage, speed garage en hard house uit Amsterdam",
      slots: [] },
    { id: "itz3bby", name: "Itz3bby", type: "muziek", genres: ["uk bass"], tip: true,
      desc: "uk bass uit Rotterdam, vet!",
      slots: [] },
    { id: "jan-koster", name: "Jan Koster", type: "muziek", genres: ["eclectic"], tip: false,
      desc: "jonge gast die echt alles door elkaar en aan elkaar mixed. Verwacht elke twee minuten een nieuwe plaat.",
      slots: [] },
    { id: "laura-meester", name: "Laura Meester", type: "muziek", genres: ["house", "uk garage", "soul"], tip: true,
      desc: "groovy soulful house, tikt ook de uk garage aan, lekker!",
      slots: [] },
    { id: "merel-helderman", name: "Merel Helderman", type: "muziek", genres: ["house", "spacy"], tip: false,
      desc: "produceert best wel toffe nummers. Beetje spacy, wazige kippen house 🐓",
      slots: [] }
  ]
};
