/* ========================================================================
   Landjuweel 2026 — het programma per dag.
   Overgenomen uit de officiële Landjuweel-app (do: 15 juli, vr/za/zo: 22 juli 2026).
   Volgorde binnen een dag maakt niet uit; de app sorteert zelf op tijd.
   Tijden na middernacht (00:00–05:00) horen bij de nacht van die dag.
   ======================================================================== */

var LINEUP = {

  do: [
    { tijd: "12:00", naam: "De VerwonderBus", podium: "Dorpsplein - Veld" },
    { tijd: "12:30", naam: "Origin Circle", podium: "Theo's Theetuin" },
    { tijd: "13:00", naam: "4-Hands Massage Arnaud Mooij & Marcel Maurik", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "14:00", naam: "Bouw mee aan het groeiende insectendorp - Het landschap", podium: "Dorpsplein - De Wereld in Wording" },
    { tijd: "14:00", naam: "Poppenkastvoorstelling", podium: "Randprogramma" },
    { tijd: "14:00", naam: "DAF - Dutch Acid Family", podium: "DAF/ Rafelrand" },
    { tijd: "14:00", naam: "De Spelletjeskast", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "XXL spellen: Schaken, Jenga, Twister", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "Photo Booth", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "Open Mic", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "! RED HET GROENE VELD - TEKEN NU !", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "Bouke en co: Gratis kleding halen & brengen", podium: "Area 46" },
    { tijd: "14:00", naam: "Rochelle Dietz", podium: "Sloôoase" },
    { tijd: "14:00", naam: "Bakfietsband", podium: "Randprogramma" },
    { tijd: "14:00", naam: "Rasta Robert & Friends", podium: "Natural High - Mama Ger" },
    { tijd: "14:00", naam: "Kloek", podium: "Dorpsplein - Veld" },
    { tijd: "14:00", naam: "De Drijvende dichter", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "Lach Workshop", podium: "Area 46" },
    { tijd: "14:00", naam: "Stemvork Healing door Shamatty", podium: "Kabouterhuys" },
    { tijd: "14:00", naam: "Kids Show door Jozefien", podium: "Kabouterhuys" },
    { tijd: "14:30", naam: "Heart Chakra Meditation", podium: "Natural High - Tipi" },
    { tijd: "14:30", naam: "Embodied Dating Club", podium: "Natural High - Kleine Yurt" },
    { tijd: "14:30", naam: "Tender Moments", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "14:30", naam: "Chi Kung met Erik Arty", podium: "Kabouterhuys" },
    { tijd: "14:30", naam: "Self Wellness Practice", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "15:00", naam: "Klei Jezelf Blij Workshop", podium: "Area 46" },
    { tijd: "15:00", naam: "Divine Mistress of Craziness", podium: "Randprogramma" },
    { tijd: "15:00", naam: "HONOUR*REVIVE*SHARE - The Workshop", podium: "Kikvors: Metamorphosis" },
    { tijd: "15:00", naam: "Festival make-upmakeover met Shotgun Cilla", podium: "Kabouterhuys" },
    { tijd: "15:00", naam: "Tarot & YOU with BHASHA", podium: "Kabouterhuys" },
    { tijd: "15:00", naam: "Silk Fans workshop - hosted by Tara Moon", podium: "Randprogramma" },
    { tijd: "15:30", naam: "Ik Cacao van Jou! - Openingsceremonie", podium: "Temple of Self" },
    { tijd: "16:00", naam: "Saskia Schmink", podium: "Dorpsplein - Veld" },
    { tijd: "16:00", naam: "Soep en broodjes", podium: "Dorpsplein - Trommelvuur" },
    { tijd: "16:00", naam: "Verhaal met The Troubadour Car", podium: "Dorpsplein - Podium Instrumentaal" },
    { tijd: "16:00", naam: "Bon Bon Vivant chocolate tasting", podium: "Bon Bon Vivant" },
    { tijd: "16:00", naam: "Algarabía - Bardo Teatro Físico", podium: "Theaterveld" },
    { tijd: "16:00", naam: "Workshop Lino Stempelen", podium: "Dorpsplein - Aardewerk" },
    { tijd: "16:00", naam: "Dromenvangers maken", podium: "Dorpsplein - Aardewerk" },
    { tijd: "16:00", naam: "Opening Festival", podium: "Krater" },
    { tijd: "16:00", naam: "Eric, de Magiër achter het rookgordijn", podium: "Kabouterhuys" },
    { tijd: "16:00", naam: "Het Poppen circus", podium: "Dorpsplein - Why Not Theater" },
    { tijd: "16:30", naam: "Landing Yoga", podium: "Kaleido Workshop Rietreat" },
    { tijd: "17:00", naam: "DJ Elektrolux", podium: "Kabouterpodium" },
    { tijd: "17:00", naam: "Poi workshop by Hidde (Hidden Flow)", podium: "Randprogramma" },
    { tijd: "17:00", naam: "InstrumMensen freestyle rap sessie", podium: "Dorpsplein - Podium Instrumentaal" },
    { tijd: "17:00", naam: "Bouw mee aan het groeiende insectendorp - Het landschap", podium: "Dorpsplein - De Wereld in Wording" },
    { tijd: "17:00", naam: "Wakhan Project", podium: "Sloôoase" },
    { tijd: "17:00", naam: "Ari's Classical Radio Show: Can You Händle It?", podium: "Bon Bon Vivant" },
    { tijd: "17:00", naam: "Taste of Tantra (Authentic Relating) van Tamara Groen", podium: "Temple of Self" },
    { tijd: "17:30", naam: "DIY Ecstatic Bodywork — release & activation", podium: "Natural High - Kleine Yurt" },
    { tijd: "17:30", naam: "Magdalena Rose Codes", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "17:30", naam: "Northern Roots – body, nature & connection", podium: "Natural High - Tipi" },
    { tijd: "17:45", naam: "Wild Grace", podium: "Theo's Theetuin" },
    { tijd: "18:00", naam: "Muziek Tapijt", podium: "Dorpsplein - Podium Instrumentaal" },
    { tijd: "18:00", naam: "Woven Voices Opening met Lex Empress", podium: "Dorpsplein - Terraspodium" },
    { tijd: "18:00", naam: "Flirting for people who are terrible at it", podium: "Kaleido Workshop Rietreat" },
    { tijd: "18:00", naam: "Nevula and the Dragon's Tale", podium: "Krater" },
    { tijd: "18:00", naam: "Gestos", podium: "Salon" },
    { tijd: "18:00", naam: "Organic Sound Group", podium: "Vlindertuin" },
    { tijd: "18:00", naam: "Boogie Family Opening", podium: "Boogie Bos" },
    { tijd: "18:30", naam: "Algarabía - Bardo Teatro Físico", podium: "Theaterveld" },
    { tijd: "18:45", naam: "Heart Songs with Ukulele by Immy Angel", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "19:00", naam: "DJ Witte Aap", podium: "Krater" },
    { tijd: "19:00", naam: "Improvisatie theater", podium: "Natural High - Kleine Yurt" },
    { tijd: "19:00", naam: "Speeddaten", podium: "De Speeltuin" },
    { tijd: "19:00", naam: "Ecstatic Dance with Dj B.ART", podium: "Temple of Self" },
    { tijd: "19:00", naam: "Flamenco - Todo es de color", podium: "Theo's Theetuin" },
    { tijd: "19:00", naam: "Merlijn Nash", podium: "Wilgenportaal" },
    { tijd: "19:00", naam: "Leef vanuit je innerlijke wijsheid", podium: "Natural High - Tipi" },
    { tijd: "19:00", naam: "Breathwork", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "19:00", naam: "Ruigoord Rebels", podium: "Rebel Stage" },
    { tijd: "19:30", naam: "Heiko Dijker's Alien Roots", podium: "Salon" },
    { tijd: "19:30", naam: "Authentiek & verbindend communiceren", podium: "Kaleido Workshop Rietreat" },
    { tijd: "19:30", naam: "Juliska", podium: "Kabouterpodium" },
    { tijd: "19:30", naam: "Music UPLifting Handpan Experience", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "20:00", naam: "The Elements Fellowship", podium: "Krater" },
    { tijd: "20:00", naam: "Ctd Movement", podium: "Dorpsplein - Terraspodium" },
    { tijd: "20:00", naam: "Purple Flame", podium: "Sloôoase" },
    { tijd: "20:00", naam: "Shimon presents Radio Border: Sunbelt Sounds", podium: "Bon Bon Vivant" },
    { tijd: "20:00", naam: "Trash Skeleton", podium: "Kerk - Punken voor Eigen Parochie" },
    { tijd: "20:00", naam: "Rave Baby - Sandra Kaas", podium: "Theaterveld" },
    { tijd: "20:00", naam: "Yanic", podium: "Boogie Bos" },
    { tijd: "20:00", naam: "Fire & Cacao Circle", podium: "Theo's Theetuin" },
    { tijd: "21:00", naam: "The Bard's Horn", podium: "Randprogramma" },
    { tijd: "21:00", naam: "HAN Here And Now", podium: "Salon" },
    { tijd: "21:00", naam: "The Perculators", podium: "Wilgenportaal" },
    { tijd: "21:00", naam: "DJ Witte Aap", podium: "Krater" },
    { tijd: "21:00", naam: "Kiss My Knoblauch", podium: "Kerk - Punken voor Eigen Parochie" },
    { tijd: "21:00", naam: "Toscan's Brew", podium: "Kabouterpodium" },
    { tijd: "21:00", naam: "Get Painted", podium: "Kaleido Workshop Rietreat" },
    { tijd: "21:00", naam: "Landjuweel Temple Space", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "21:00", naam: "The Unemployed", podium: "Rebel Stage" },
    { tijd: "21:00", naam: "Victor Sams op Ngoni", podium: "Dorpsplein - Trommelvuur" },
    { tijd: "21:00", naam: "DJ Babette", podium: "Kaleido Queer Stage" },
    { tijd: "21:00", naam: "DJ Steve Kennedy", podium: "De Speeltuin" },
    { tijd: "21:30", naam: "Wormhol DJ", podium: "Boogie Bos" },
    { tijd: "21:30", naam: "DJ FeelofSofie", podium: "Temple of Self" },
    { tijd: "22:00", naam: "The Underbouncers", podium: "Wilgenportaal" },
    { tijd: "22:00", naam: "JPattersson", podium: "Krater" },
    { tijd: "22:00", naam: "The Rise, Life and Death of Don Quijote", podium: "Kikvors: Metamorphosis" },
    { tijd: "22:00", naam: "Mantra Kirtan", podium: "Theo's Theetuin" },
    { tijd: "22:00", naam: "Dj Deun Legal Alien", podium: "Area 46" },
    { tijd: "22:00", naam: "Fooi", podium: "Kerk - Punken voor Eigen Parochie" },
    { tijd: "22:00", naam: "Earth Garden", podium: "Randprogramma" },
    { tijd: "22:00", naam: "Bliz Nochi (live)", podium: "Sloôoase" },
    { tijd: "22:00", naam: "Djembefola's", podium: "Dorpsplein - Trommelvuur" },
    { tijd: "22:30", naam: "SUNN", podium: "Salon" },
    { tijd: "23:00", naam: "Doris Fiore", podium: "Boogie Bos" },
    { tijd: "23:00", naam: "Esta Polyesta", podium: "Krater" },
    { tijd: "23:00", naam: "Duin", podium: "Kikvors: Metamorphosis" },
    { tijd: "23:00", naam: "Bring the Joints", podium: "Kabouterpodium" },
    { tijd: "23:00", naam: "Gente Quente", podium: "Bon Bon Vivant" },
    { tijd: "23:00", naam: "Uitzendbureau", podium: "Kerk - Punken voor Eigen Parochie" },
    { tijd: "23:30", naam: "DJ YΔRL b2b Kahmeya", podium: "Temple of Self" },
    { tijd: "00:00", naam: "DJ Merlin", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "Lowfire", podium: "Salon" },
    { tijd: "00:00", naam: "Jamsessie met the Improvinators", podium: "Rebel Stage" },
    { tijd: "00:00", naam: "Soul Safari", podium: "Sloôoase" },
    { tijd: "00:00", naam: "L.A. Sagne", podium: "Kerk - Punken voor Eigen Parochie" },
    { tijd: "00:00", naam: "DJ Sucre", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Vage Paul", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Snow Whitney", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Rump3lst!lsk!", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Ellis in Wonderland", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "Dj Fred Legal Alien", podium: "Area 46" },
    { tijd: "00:00", naam: "Ippy", podium: "Wilgenportaal" },
    { tijd: "00:30", naam: "DJ Captain Spank b2b DJ MacGyver 2.0", podium: "Kabouterpodium" },
    { tijd: "00:30", naam: "DJ JP", podium: "De Speeltuin" },
    { tijd: "00:30", naam: "Abelix", podium: "Boogie Bos" },
    { tijd: "01:00", naam: "Kayva van Gangelen & Piet Jan Blauw", podium: "Krater" },
    { tijd: "01:15", naam: "Zibabu", podium: "Kerk - Punken voor Eigen Parochie" },
    { tijd: "01:30", naam: "Sem Kramer & Cherry", podium: "Salon" },
    { tijd: "02:00", naam: "Kaje Row", podium: "Sloôoase" },
    { tijd: "02:00", naam: "B2B Solame vs FTGRL", podium: "Kerk - Punken voor Eigen Parochie" },
    { tijd: "02:00", naam: "Night Drumming", podium: "Dorpsplein - Trommelvuur" },
    { tijd: "02:00", naam: "Dj Chaakra Legal Alien", podium: "Area 46" },
    { tijd: "02:30", naam: "yak x mari posa", podium: "Boogie Bos" }
  ],

  vr: [
    { tijd: "09:00", naam: "Kinder Kamping", podium: "Camping" },
    { tijd: "11:00", naam: "Morning Yoga - De 5 Elementen Vorm", podium: "Camping" },
    { tijd: "12:00", naam: "Bakfietsband", podium: "Randprogramma" },
    { tijd: "12:00", naam: "Bouw mee aan het groeiende insectendorp - Het plantenrijk", podium: "Dorpsplein - De Wereld in Wording" },
    { tijd: "12:00", naam: "Coco Coquelicot story telling", podium: "Bon Vivant" },
    { tijd: "12:00", naam: "De VerwonderBus", podium: "Dorpsplein - Veld" },
    { tijd: "12:00", naam: "De zachte landing", podium: "Dorpsplein - Podium Instrumentaal" },
    { tijd: "12:00", naam: "Earth Garden", podium: "Randprogramma" },
    { tijd: "12:00", naam: "Kloek", podium: "Dorpsplein - Veld" },
    { tijd: "12:00", naam: "Lizard Yoga", podium: "Kikvors: Metamorphosis" },
    { tijd: "12:00", naam: "Performances - Friday", podium: "Bon Vivant" },
    { tijd: "12:00", naam: "Poppenkastvoorstelling", podium: "Randprogramma" },
    { tijd: "12:00", naam: "Woven Voices", podium: "Dorpsplein - Terraspodium Woven Voices" },
    { tijd: "12:00", naam: "Ámika", podium: "Sloôoase" },
    { tijd: "12:30", naam: "Dansjewel : Inphiknight", podium: "Krater" },
    { tijd: "12:30", naam: "Het Beeldjuweel op Vrijdag", podium: "Kerk - Het Beeldjuweel" },
    { tijd: "12:30", naam: "Origin Circle", podium: "Theo's Theetuin" },
    { tijd: "13:00", naam: "'Poésies du Feu et de la Terre'", podium: "Dorpsplein - Veld" },
    { tijd: "13:00", naam: "4-Hands Massage Arnaud Mooij & Marcel Maurik", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "13:00", naam: "Baba Exotica", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "13:00", naam: "Bouke en co: Gratis kleding halen & brengen", podium: "Area 46" },
    { tijd: "13:00", naam: "Chakra journey", podium: "Natural High - Tipi" },
    { tijd: "13:00", naam: "Contact with Movement", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "13:00", naam: "Friction - Compagnie Fô-Pá", podium: "Dorpsplein - Why Not Theater" },
    { tijd: "13:00", naam: "Hoop Workshop by Iris Dam Hoops", podium: "Randprogramma" },
    { tijd: "13:00", naam: "Informatief: Huiden verwerken", podium: "Dorpsplein - Aardewerk" },
    { tijd: "13:00", naam: "Kaleidoscope - hosted by Quinten", podium: "Wilgenportaal" },
    { tijd: "13:00", naam: "Ontwaakceremonie met Sophia Maria Kienhuis en Gilian Baracs", podium: "Dorpsplein - Terraspodium Woven Voices" },
    { tijd: "13:00", naam: "Rasta Robert & Friends", podium: "Natural High - Mama Ger" },
    { tijd: "13:00", naam: "Saskia Schmink", podium: "Dorpsplein - Veld" },
    { tijd: "13:00", naam: "Shamanic Healing Journey", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "13:00", naam: "Verwonderworkshop", podium: "Dorpsplein - Why Not Theater" },
    { tijd: "13:00", naam: "Vinyasa yoga en ademwerk", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "13:00", naam: "Workshop Lino Stempelen", podium: "Dorpsplein - Aardewerk" },
    { tijd: "13:30", naam: "One-Line Art workshop", podium: "Kaleido Workshop Rietreat" },
    { tijd: "13:30", naam: "Qi Gong Ochtend Sessie van Maarten Collewijn", podium: "Temple of Self" },
    { tijd: "13:30", naam: "Smooth Awakenings", podium: "Kaleido Queer Stage" },
    { tijd: "14:00", naam: "! RED HET GROENE VELD - TEKEN NU!", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "Awakening Dance", podium: "Kerk - Kaleido Takeover" },
    { tijd: "14:00", naam: "Dansworkshop: Organic movement Dance\"", podium: "Krater" },
    { tijd: "14:00", naam: "De Drijvende dichter", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "De Geluiden-Fabriek & HetVerzin-Het-Ter-Plekke Spel", podium: "Dorpsplein - Why Not Theater" },
    { tijd: "14:00", naam: "De Spelletjeskast", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "Filosofisch kabinet", podium: "Dorpsplein - Veld" },
    { tijd: "14:00", naam: "Gurdieff Kwartet", podium: "Vlindertuin" },
    { tijd: "14:00", naam: "Kids Show door Jozefien", podium: "Kabouterhuys" },
    { tijd: "14:00", naam: "Lach Workshop", podium: "Area 46" },
    { tijd: "14:00", naam: "MC Katootje", podium: "Dorpsplein - Podium Instrumentaal" },
    { tijd: "14:00", naam: "Morning Yoga - De 5 Elementen Vorm", podium: "Theo's Theetuin" },
    { tijd: "14:00", naam: "Photo Booth", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "Reiki & Just Zen It Workshop (12+jaar)", podium: "Dorpsplein - Aardewerk" },
    { tijd: "14:00", naam: "Stemvork Healing door Shamatty", podium: "Kabouterhuys" },
    { tijd: "14:00", naam: "The Art of Belonging", podium: "Salon" },
    { tijd: "14:00", naam: "The Wellness Hosting Hour", podium: "Kaleido Queer Stage" },
    { tijd: "14:00", naam: "Transform Yourself", podium: "Kaleido Faerie Forest" },
    { tijd: "14:00", naam: "Waterpret: babbelbad & watergevecht", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "Workshop FreePlay Movement", podium: "Theaterveld" },
    { tijd: "14:00", naam: "Workshop: Huiden verwerken", podium: "Dorpsplein - Aardewerk" },
    { tijd: "14:00", naam: "XXL spellen: Schaken, Jenga, Twister", podium: "De Speeltuin" },
    { tijd: "14:30", naam: "Chi Kung met Erik Arty", podium: "Kabouterhuys" },
    { tijd: "14:30", naam: "SanghaSang & Swierstra", podium: "Sloôoase" },
    { tijd: "14:45", naam: "Move & Play: Buddy Fitness", podium: "Kerk - Kaleido Takeover" },
    { tijd: "15:00", naam: "Contact Staff Workshop hosted by The Fire Messiah", podium: "Randprogramma" },
    { tijd: "15:00", naam: "DAF - Dutch Acid Family", podium: "DAF/ Rafelrand" },
    { tijd: "15:00", naam: "Divine Mistress of Craziness", podium: "Randprogramma" },
    { tijd: "15:00", naam: "Ecstatic Dance with", podium: "Temple of Self" },
    { tijd: "15:00", naam: "Een talisman borduren", podium: "Dorpsplein - De Wereld in Wording" },
    { tijd: "15:00", naam: "Festival make-up/makeover met Shotgun Cilla", podium: "Kabouterhuys" },
    { tijd: "15:00", naam: "Florelei", podium: "Theo's Theetuin" },
    { tijd: "15:00", naam: "FreeFlow Flashmob", podium: "Randprogramma" },
    { tijd: "15:00", naam: "Gotcha & Katherina - folkloristische liederen uit Georgië", podium: "Kabouterpodium" },
    { tijd: "15:00", naam: "Henk en de Straaljager: all age kinderdisco", podium: "Bon Vivant" },
    { tijd: "15:00", naam: "Job den Dulk", podium: "Vlindertuin" },
    { tijd: "15:00", naam: "Kalaudo", podium: "Kaleido Queer Stage" },
    { tijd: "15:00", naam: "Latin percussion workshop met Jos de Haas", podium: "Dorpsplein - Veld" },
    { tijd: "15:00", naam: "Legend Drum workshop", podium: "Dorpsplein - Veld" },
    { tijd: "15:00", naam: "Marcia's Metal Masquerade", podium: "Kikvors: Metamorphosis" },
    { tijd: "15:00", naam: "MariGlue", podium: "Boogie Bos" },
    { tijd: "15:00", naam: "Queer Platonic Speeddating", podium: "Kaleido Workshop Rietreat" },
    { tijd: "15:00", naam: "ROOTEDANCE", podium: "Krater" },
    { tijd: "15:00", naam: "Soep en broodjes", podium: "Dorpsplein - Veld" },
    { tijd: "15:00", naam: "Tarot & YOU with BHASHA", podium: "Kabouterhuys" },
    { tijd: "15:00", naam: "The Bard's Horn", podium: "Randprogramma" },
    { tijd: "15:30", naam: "Drugs Zonder Drugs", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "15:30", naam: "Inner Child Garden", podium: "Kerk - Kaleido Takeover" },
    { tijd: "15:30", naam: "Kinder Catwalk", podium: "Kaleido Workshop Rietreat" },
    { tijd: "15:30", naam: "Love Yourself' workshop", podium: "Natural High - Tipi" },
    { tijd: "15:30", naam: "Somatic Playground", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "15:30", naam: "Sound Journey met Rinco & Stéphanie van Wij Zijn Bloei", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "15:30", naam: "Wim Hof Methode Ijsbad", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "16:00", naam: "Cronos - Bardo Teatro Físico", podium: "Theaterveld" },
    { tijd: "16:00", naam: "De Rebellenklup: Julius Joker & Erwin Mulder", podium: "Kabouterpodium" },
    { tijd: "16:00", naam: "Elena Tierra", podium: "Salon" },
    { tijd: "16:00", naam: "Eline Bierling & Mame N'Diack: De Bedoeling", podium: "Krater" },
    { tijd: "16:00", naam: "Eric, de Magiër achter het rookgordijn", podium: "Kabouterhuys" },
    { tijd: "16:00", naam: "Het Woord o.I.v. Yvonne van Doorn en Diana Ozon", podium: "Randprogramma" },
    { tijd: "16:00", naam: "Lisa en de bruine prins", podium: "Dorpsplein - Podium Instrumentaal" },
    { tijd: "16:00", naam: "Marble Workshop", podium: "Area 46" },
    { tijd: "16:00", naam: "Poetry Consults", podium: "Kaleido Faerie Forest" },
    { tijd: "16:00", naam: "Ralph de Jongh & Roos Kanis", podium: "Theo's Theetuin" },
    { tijd: "16:00", naam: "Roberta Petzoldt", podium: "Vlindertuin" },
    { tijd: "16:00", naam: "Trammelant in sprookjesland", podium: "Dorpsplein - Why Not Theater" },
    { tijd: "16:00", naam: "Workshop Lino Stempels maken vanaf 10 jaar", podium: "Dorpsplein - Aardewerk" },
    { tijd: "16:00", naam: "Woven Voices: What's alive in you?", podium: "Dorpsplein - Terraspodium Woven Voices" },
    { tijd: "16:00", naam: "Yanic", podium: "Sloôoase" },
    { tijd: "16:30", naam: "Babette", podium: "Dorpsplein - Podium Instrumentaal" },
    { tijd: "16:30", naam: "K-Faeries Training", podium: "Kaleido Queer Stage" },
    { tijd: "16:30", naam: "Pull & Power", podium: "Kerk - Kaleido Takeover" },
    { tijd: "16:30", naam: "Siren Rising", podium: "Kaleido Workshop Rietreat" },
    { tijd: "17:00", naam: "DJ Witte Aap", podium: "Krater" },
    { tijd: "17:00", naam: "Estée & Michel", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "17:00", naam: "Goey & Kirkos", podium: "Vlindertuin" },
    { tijd: "17:00", naam: "Jolly Mango's", podium: "Rebel Stage" },
    { tijd: "17:00", naam: "La Prudon x Ibu Ibiza - Hoeden & Modeshow", podium: "Randprogramma" },
    { tijd: "17:00", naam: "Laura Jayne", podium: "Boogie Bos" },
    { tijd: "17:00", naam: "Leadbeaters", podium: "Wilgenportaal" },
    { tijd: "17:00", naam: "Op je lijf geschreven verhaal", podium: "Dorpsplein - Veld" },
    { tijd: "17:00", naam: "Spin Fans workshop hosted by Tara Moon", podium: "Randprogramma" },
    { tijd: "17:00", naam: "Tattoo Station", podium: "Kaleido Faerie Forest" },
    { tijd: "17:00", naam: "Workshop Playful Partner Yoga", podium: "Theaterveld" },
    { tijd: "17:15", naam: "Ontdek Jezelf met Kunst met Fleur Cecile Haak", podium: "Temple of Self" },
    { tijd: "17:30", naam: "HONOUR*REVIVE*SHARE - The Workshop", podium: "Kikvors: Metamorphosis" },
    { tijd: "17:30", naam: "Heiko Dijker's Soul Sangam - Nava Rasa", podium: "Salon" },
    { tijd: "17:30", naam: "Join the Cult of Guru Lui Delulu", podium: "Kerk - Kaleido Takeover" },
    { tijd: "17:30", naam: "Mantra & Cacao", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "17:30", naam: "Shamballa Tribe", podium: "Theo's Theetuin" },
    { tijd: "17:30", naam: "Vallei Orgasme", podium: "Natural High - Tipi" },
    { tijd: "17:30", naam: "Willemijn Bessem Intimiteit & Verbinding", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "18:00", naam: "DJ Try/Me", podium: "Kaleido Queer Stage" },
    { tijd: "18:00", naam: "Dag afsluiting", podium: "Dorpsplein - Aardewerk" },
    { tijd: "18:00", naam: "Kelsey Kluijtmans concert", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "18:00", naam: "Kidd Nebula", podium: "Kabouterpodium" },
    { tijd: "18:00", naam: "Muziek Tapijt", podium: "Dorpsplein - Podium Instrumentaal" },
    { tijd: "18:00", naam: "Más - La Familia Volante", podium: "Dorpsplein - Why Not Theater" },
    { tijd: "18:00", naam: "Oh Voyage", podium: "Krater" },
    { tijd: "18:00", naam: "Peacock Garden Mini Retreat Bubble", podium: "Kaleido Workshop Rietreat" },
    { tijd: "18:00", naam: "Polymer", podium: "Sloôoase" },
    { tijd: "18:00", naam: "Some Chemistry: Barbecue Space Station Set", podium: "Bon Vivant" },
    { tijd: "18:00", naam: "The White Peacock Jam", podium: "Vlindertuin" },
    { tijd: "18:15", naam: "Church of the Untamed", podium: "Kerk - Kaleido Takeover" },
    { tijd: "18:30", naam: "Cronos - Bardo Teatro Físico", podium: "Theaterveld" },
    { tijd: "18:30", naam: "Riet(j)uweel voor Stembehoud met Yente & Ocean", podium: "Temple of Self" },
    { tijd: "19:00", naam: "CERA", podium: "Kerk - Kaleido Takeover" },
    { tijd: "19:00", naam: "Creatures on the Loose", podium: "Salon" },
    { tijd: "19:00", naam: "DJ Witte Aap", podium: "Krater" },
    { tijd: "19:00", naam: "Dizzy Fingers", podium: "Wilgenportaal" },
    { tijd: "19:00", naam: "Gilian Baracs and band", podium: "Dorpsplein - Terraspodium Woven Voices" },
    { tijd: "19:00", naam: "Intimate haircuts", podium: "Kaleido Faerie Forest" },
    { tijd: "19:00", naam: "Open Jam sessie", podium: "De Speeltuin" },
    { tijd: "19:00", naam: "Psychedelic Tea Party", podium: "Area 46" },
    { tijd: "19:00", naam: "Sjef Rolet", podium: "Boogie Bos" },
    { tijd: "19:00", naam: "Speeddaten", podium: "De Speeltuin" },
    { tijd: "19:00", naam: "The Beatzers", podium: "Rebel Stage" },
    { tijd: "19:30", naam: "DJ Yellow Rose", podium: "Temple of Self" },
    { tijd: "20:00", naam: "Josje & the Catalyst", podium: "Theo's Theetuin" },
    { tijd: "20:00", naam: "Landjuweel Temple Space", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "20:00", naam: "Meraki", podium: "Sloôoase" },
    { tijd: "20:00", naam: "Molly Cules", podium: "Kaleido Queer Stage" },
    { tijd: "20:00", naam: "Rave Baby - Sandra Kaas", podium: "Theaterveld" },
    { tijd: "20:00", naam: "Wasim Arslan", podium: "Krater" },
    { tijd: "20:30", naam: "Dakka Sultana", podium: "Dorpsplein - Veld" },
    { tijd: "20:30", naam: "Kitano Band", podium: "Salon" },
    { tijd: "21:00", naam: "DJ Witte Aap", podium: "Krater" },
    { tijd: "21:00", naam: "De Zevende Kleur presents: The Floating Fantasy", podium: "Bon Vivant" },
    { tijd: "21:00", naam: "Flamingo hitmix", podium: "Randprogramma" },
    { tijd: "21:00", naam: "Flavour Coalition", podium: "Rebel Stage" },
    { tijd: "21:00", naam: "GUTEN ABEND", podium: "Kerk - Kaleido Takeover" },
    { tijd: "21:00", naam: "Isaie", podium: "Boogie Bos" },
    { tijd: "21:00", naam: "Misfit Valley", podium: "Kikvors: Metamorphosis" },
    { tijd: "21:00", naam: "Motorknüller: Madmotormiquel & Heimlich Knüller", podium: "Bon Vivant" },
    { tijd: "21:00", naam: "Stray Elf", podium: "Kaleido Queer Stage" },
    { tijd: "21:15", naam: "Kosmies Wilgenportaal", podium: "Wilgenportaal" },
    { tijd: "21:30", naam: "REO MATSUMOTO DJ Set with live Handpan", podium: "Temple of Self" },
    { tijd: "22:00", naam: "CLUBSYNTH: Tectonia", podium: "Area 46" },
    { tijd: "22:00", naam: "Cedric Vermue ft Tjalle Rens", podium: "Theo's Theetuin" },
    { tijd: "22:00", naam: "Djembefola's", podium: "Dorpsplein - Veld" },
    { tijd: "22:00", naam: "INOYSON & ANYA [Hybrid Live DJ set]", podium: "Kabouterpodium" },
    { tijd: "22:00", naam: "Jimmy Moon", podium: "Krater" },
    { tijd: "22:00", naam: "Meraque", podium: "Wilgenportaal" },
    { tijd: "22:00", naam: "Rochelle Dietz", podium: "Sloôoase" },
    { tijd: "22:00", naam: "The Rise, Life and Death of Don Quijote", podium: "Kikvors: Metamorphosis" },
    { tijd: "22:30", naam: "DJ PaGLI-Indian Dance Electronica", podium: "Theo's Theetuin" },
    { tijd: "22:30", naam: "Quintens's Birthday Bash", podium: "Salon" },
    { tijd: "22:45", naam: "Anxiety as a Gift", podium: "Kikvors: Metamorphosis" },
    { tijd: "22:45", naam: "Connective tissue", podium: "Kerk - Kaleido Takeover" },
    { tijd: "23:00", naam: "CLUBSYNTH: noedels!", podium: "Area 46" },
    { tijd: "23:00", naam: "Cuervo Cuervo", podium: "Wilgenportaal" },
    { tijd: "23:00", naam: "Darkvoice", podium: "De Speeltuin" },
    { tijd: "23:00", naam: "JXSSX", podium: "Kerk - Kaleido Takeover" },
    { tijd: "23:00", naam: "Link & Herr Alt", podium: "Boogie Bos" },
    { tijd: "23:00", naam: "Spull", podium: "Rebel Stage" },
    { tijd: "23:30", naam: "DJ Witte Aap", podium: "Krater" },
    { tijd: "23:30", naam: "Klam: DJSelene b2b Daktari", podium: "Temple of Self" },
    { tijd: "23:45", naam: "The Wet and Naughty Show", podium: "Kikvors: Metamorphosis" },
    { tijd: "00:00", naam: "Andert Tysma", podium: "Sloôoase" },
    { tijd: "00:00", naam: "DJ Captain Spank", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Ellis in Wonderland", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Merlin", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Paulos", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Rump3lst!lsk!", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Snow Whitney", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Sucre", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "Jamsessie met Carlos Manso", podium: "Rebel Stage" },
    { tijd: "00:00", naam: "Spons & Draad", podium: "Kabouterpodium" },
    { tijd: "00:00", naam: "Stefnitz", podium: "Boogie Bos" },
    { tijd: "00:30", naam: "Duin", podium: "Kikvors: Metamorphosis" },
    { tijd: "00:30", naam: "Origins: Krien & Merante Heroine's Journey", podium: "Krater" },
    { tijd: "00:30", naam: "State of the Aart", podium: "De Speeltuin" },
    { tijd: "01:00", naam: "AMYIR", podium: "Area 46" },
    { tijd: "01:00", naam: "DJ Vage Paul", podium: "Kabouterpodium" },
    { tijd: "01:00", naam: "The Altar of Flesh", podium: "Kerk - Kaleido Takeover" },
    { tijd: "01:00", naam: "Xamanoz", podium: "Salon" },
    { tijd: "01:00", naam: "Вессс", podium: "Kerk - Kaleido Takeover" },
    { tijd: "01:30", naam: "Metik", podium: "Wilgenportaal" },
    { tijd: "02:00", naam: "Night Drumming", podium: "Dorpsplein - Veld" },
    { tijd: "02:00", naam: "Rhei x Kahateka", podium: "Sloôoase" },
    { tijd: "02:00", naam: "Temple DJ's", podium: "Temple of Self" },
    { tijd: "02:30", naam: "Mr Henky", podium: "Wilgenportaal" },
    { tijd: "03:00", naam: "DJ Kingston Hi Fi", podium: "Kabouterpodium" },
    { tijd: "03:00", naam: "Dj Chaakra Legal Alien", podium: "Area 46" },
    { tijd: "03:00", naam: "Jazz Dahlia", podium: "Boogie Bos" },
    { tijd: "03:00", naam: "Julietta Vendetta", podium: "Kerk - Kaleido Takeover" }
  ],

  za: [
    { tijd: "05:00", naam: "Rowel Hazelini", podium: "Wilgenportaal" },
    { tijd: "09:00", naam: "Kinder Kamping", podium: "Camping" },
    { tijd: "11:00", naam: "Morning Yoga - De 5 Elementen Vorm", podium: "Camping" },
    { tijd: "12:00", naam: "Bakfietsband", podium: "Randprogramma" },
    { tijd: "12:00", naam: "Bouw mee aan het groeiende insectendorp - De luchtwezens", podium: "Dorpsplein - De Wereld in Wording" },
    { tijd: "12:00", naam: "DAF - Dutch Acid Family", podium: "DAF/ Rafelrand" },
    { tijd: "12:00", naam: "De VerwonderBus", podium: "Dorpsplein - Veld" },
    { tijd: "12:00", naam: "De zachte landing", podium: "Dorpsplein - Why Not Theater" },
    { tijd: "12:00", naam: "Earth Garden", podium: "Randprogramma" },
    { tijd: "12:00", naam: "Kloek", podium: "Dorpsplein - Veld" },
    { tijd: "12:00", naam: "Lizard Yoga", podium: "Kikvors: Metamorphosis" },
    { tijd: "12:00", naam: "Misjael Monteban 'Love Songs'", podium: "Bon Vivant" },
    { tijd: "12:00", naam: "Performances - Saturday", podium: "Bon Vivant" },
    { tijd: "12:00", naam: "Poppenkastvoorstelling", podium: "Randprogramma" },
    { tijd: "12:00", naam: "Rodmer", podium: "Sloôoase" },
    { tijd: "12:00", naam: "Woven Voices", podium: "Dorpsplein - Terraspodium Woven Voices" },
    { tijd: "12:30", naam: "Dansjewel : Laura Jayne", podium: "Krater" },
    { tijd: "12:30", naam: "Koffie met Jan", podium: "Wilgenportaal" },
    { tijd: "12:30", naam: "Origin Circle", podium: "Theo's Theetuin" },
    { tijd: "12:30", naam: "Sophia Maria Kienhuis", podium: "Dorpsplein - Terraspodium Woven Voices" },
    { tijd: "13:00", naam: "'Poésies du Feu et de la Terre'", podium: "Dorpsplein - Veld" },
    { tijd: "13:00", naam: "4-Hands Massage Arnaud Mooij & Marcel Maurik", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "13:00", naam: "Bouke en co: Gratis kleding halen & brengen", podium: "Area 46" },
    { tijd: "13:00", naam: "FlowerSticks Workshop hosted by Rene FocusFire", podium: "Randprogramma" },
    { tijd: "13:00", naam: "Garden of Devotion", podium: "Randprogramma" },
    { tijd: "13:00", naam: "Informatief: Huiden verwerken", podium: "Dorpsplein - Aardewerk" },
    { tijd: "13:00", naam: "Más - La Familia Volante", podium: "Dorpsplein - Why Not Theater" },
    { tijd: "13:00", naam: "Open Your Heart' Ademreis", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "13:00", naam: "Rasta Robert & Friends", podium: "Natural High - Mama Ger" },
    { tijd: "13:00", naam: "Saskia Schmink", podium: "Dorpsplein - Veld" },
    { tijd: "13:00", naam: "Shake The Dust", podium: "Natural High - Tipi" },
    { tijd: "13:00", naam: "Sound Medicine Journey with Tessa & Sjoerd", podium: "Temple of Self" },
    { tijd: "13:00", naam: "Till Glitter Do Us Part", podium: "Kaleido Queer Stage" },
    { tijd: "13:00", naam: "Vrouwencirkel - De Stem van je Voormoeders", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "13:00", naam: "Workshop Lino Stempelen", podium: "Dorpsplein - Aardewerk" },
    { tijd: "13:00", naam: "Workshop vuur maken door Robert Bleij", podium: "Dorpsplein - Aardewerk" },
    { tijd: "13:30", naam: "Het Beeldjuweel op Zaterdag", podium: "Kerk - Het Beeldjuweel" },
    { tijd: "13:30", naam: "Morning Yoga - De 5 Elementen Vorm", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "14:00", naam: "! RED HET GROENE VELD - TEKEN NU!", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "(H)oer Hollandse spelletjes", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "AfroMix", podium: "Krater" },
    { tijd: "14:00", naam: "Consent Bingo", podium: "Kaleido Workshop Rietreat" },
    { tijd: "14:00", naam: "De Drijvende dichter", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "De Spelletjeskast", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "Dougal Hallowes - Sitar Journeys", podium: "Vlindertuin" },
    { tijd: "14:00", naam: "Filosofisch kabinet", podium: "Dorpsplein - Veld" },
    { tijd: "14:00", naam: "Hidden Bamboo Garden", podium: "Randprogramma" },
    { tijd: "14:00", naam: "Kids Show door Jozefien", podium: "Kabouterhuys" },
    { tijd: "14:00", naam: "Lach Workshop", podium: "Area 46" },
    { tijd: "14:00", naam: "Muziek verhaal met The Troubadour Car", podium: "Dorpsplein - Podium Instrumentaal" },
    { tijd: "14:00", naam: "Photo Booth", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "Poetry Consults", podium: "Kaleido Faerie Forest" },
    { tijd: "14:00", naam: "Psychedelic Salon", podium: "Salon" },
    { tijd: "14:00", naam: "Reiki & Just Zen It Workshop (12+ jaar)", podium: "Dorpsplein - Aardewerk" },
    { tijd: "14:00", naam: "Spiritual Battleground", podium: "Kaleido Queer Stage" },
    { tijd: "14:00", naam: "Stemvork Healing door Shamatty", podium: "Kabouterhuys" },
    { tijd: "14:00", naam: "Workshop Playfight", podium: "Theaterveld" },
    { tijd: "14:00", naam: "Workshop: Huiden verwerken", podium: "Dorpsplein - Aardewerk" },
    { tijd: "14:00", naam: "Woven Voices: What's alive in you?", podium: "Dorpsplein - Terraspodium Woven Voices" },
    { tijd: "14:00", naam: "XXL spellen: Schaken, Jenga, Twister", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "Yin Yoga", podium: "Theo's Theetuin" },
    { tijd: "14:15", naam: "DragonStaff workshop by Sem", podium: "Randprogramma" },
    { tijd: "14:30", naam: "Chi Kung met Erik Arty", podium: "Kabouterhuys" },
    { tijd: "14:30", naam: "Voorleesmeditatie door Simone Bijlard met live handpan van Reo Matsumoto", podium: "Temple of Self" },
    { tijd: "14:45", naam: "FreeFlow Flashmob", podium: "Randprogramma" },
    { tijd: "14:45", naam: "Nereo", podium: "Wilgenportaal" },
    { tijd: "15:00", naam: "Divine Mistress of Craziness", podium: "Randprogramma" },
    { tijd: "15:00", naam: "Een caleidoscoop maken - De verrekijker van het vliegende wezen", podium: "Dorpsplein - De Wereld in Wording" },
    { tijd: "15:00", naam: "Festival make-up/makeover met Shotgun Cilla", podium: "Kabouterhuys" },
    { tijd: "15:00", naam: "JRK x Maud", podium: "Sloôoase" },
    { tijd: "15:00", naam: "Legend Drum workshop", podium: "Dorpsplein - Veld" },
    { tijd: "15:00", naam: "Lotte Walda", podium: "Vlindertuin" },
    { tijd: "15:00", naam: "Prime Time Power Throuple", podium: "Kaleido Queer Stage" },
    { tijd: "15:00", naam: "Soep en broodjes", podium: "Dorpsplein - Veld" },
    { tijd: "15:00", naam: "Stoievaar x Vrolijke Vogelaar", podium: "Boogie Bos" },
    { tijd: "15:00", naam: "Talking drum workshop met Mame N'Diack", podium: "Dorpsplein - Veld" },
    { tijd: "15:00", naam: "Tarot & YOU with BHASHA", podium: "Kabouterhuys" },
    { tijd: "15:00", naam: "Thara Bergen: Coco Blance Hip Hop Set", podium: "Bon Vivant" },
    { tijd: "15:00", naam: "The Bard's Horn", podium: "Randprogramma" },
    { tijd: "15:00", naam: "Voices Revelation", podium: "Kabouterpodium" },
    { tijd: "15:15", naam: "BINGO!!!", podium: "Kaleido Queer Stage" },
    { tijd: "15:30", naam: "Blindfolded Self Connection with Josefine Adriana", podium: "Temple of Self" },
    { tijd: "15:30", naam: "Buiten Podium met: Sylvia van Swieten, Mohammed Cissewko,Lasana Camera en Amara Diabate", podium: "Salon" },
    { tijd: "15:30", naam: "Dragtivism Workshop", podium: "Kaleido Workshop Rietreat" },
    { tijd: "15:30", naam: "In het Hart", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "15:30", naam: "Introduction to Club Juggling by Nakarit and Nico", podium: "Randprogramma" },
    { tijd: "15:30", naam: "Le Miracle du Vivant by: Marchal", podium: "Bon Vivant" },
    { tijd: "15:30", naam: "Mahfil Duo Ali Seif", podium: "Theo's Theetuin" },
    { tijd: "15:30", naam: "Sensual Snacks", podium: "Natural High - Tipi" },
    { tijd: "15:30", naam: "Tender Tantric Dance", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "15:30", naam: "Zangcirkel & Soundhealing", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "16:00", naam: "Dromenvangers maken", podium: "Dorpsplein - Aardewerk" },
    { tijd: "16:00", naam: "Eric, de Magiër achter het rookgordijn", podium: "Kabouterhuys" },
    { tijd: "16:00", naam: "Estroe", podium: "Wilgenportaal" },
    { tijd: "16:00", naam: "INOYSON: Lucid Dreams Universe", podium: "Krater" },
    { tijd: "16:00", naam: "Kagiso Universalis", podium: "Vlindertuin" },
    { tijd: "16:00", naam: "Klei Jezelf Blij Workshop", podium: "Area 46" },
    { tijd: "16:00", naam: "MC Katootje", podium: "Dorpsplein - Podium Instrumentaal" },
    { tijd: "16:00", naam: "Marly Niyambura", podium: "Dorpsplein - Terraspodium Woven Voices" },
    { tijd: "16:00", naam: "Pote CompLote - Las Corpa", podium: "Theaterveld" },
    { tijd: "16:00", naam: "Trammelant in sprookjesland", podium: "Dorpsplein - Why Not Theater" },
    { tijd: "16:00", naam: "Wierd Dijkstra", podium: "Kabouterpodium" },
    { tijd: "16:00", naam: "Workshop Lino Stempels maken vanaf 10 jaar", podium: "Dorpsplein - Aardewerk" },
    { tijd: "16:30", naam: "Ecstatic Dance & Breathflow with DJ YARL & Eline Bouma", podium: "Temple of Self" },
    { tijd: "16:45", naam: "Jungle of Wires", podium: "Wilgenportaal" },
    { tijd: "17:00", naam: "DJ Witte Aap", podium: "Krater" },
    { tijd: "17:00", naam: "Etherion", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "17:00", naam: "Goey & Kirkos", podium: "Vlindertuin" },
    { tijd: "17:00", naam: "Lisa en de bruine prins", podium: "Dorpsplein - Podium Instrumentaal" },
    { tijd: "17:00", naam: "Ralph de Jongh & Roos Kanis", podium: "Rebel Stage" },
    { tijd: "17:00", naam: "Roswitha B2B Carmen", podium: "Boogie Bos" },
    { tijd: "17:00", naam: "Soul song met Lex", podium: "Dorpsplein - Why Not Theater" },
    { tijd: "17:00", naam: "Soulsong", podium: "Dorpsplein - Why Not Theater" },
    { tijd: "17:00", naam: "Sumanth Manjunath & Quinten Rutgers", podium: "Theo's Theetuin" },
    { tijd: "17:00", naam: "Workshop Resonance Movement Playground", podium: "Theaterveld" },
    { tijd: "17:30", naam: "Babette", podium: "Dorpsplein - Podium Instrumentaal" },
    { tijd: "17:30", naam: "Couple Positive", podium: "Salon" },
    { tijd: "17:30", naam: "Shamanic Breath", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "17:30", naam: "State of Being", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "17:30", naam: "Tantric Shibari Workshop: how to play with Ropes", podium: "Natural High - Tipi" },
    { tijd: "17:45", naam: "Walhallala", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "18:00", naam: "Aron Friedman's Psychedelic Mirror Ball", podium: "Bon Vivant" },
    { tijd: "18:00", naam: "Bang. Boos. Bedroefd. Blij", podium: "Kaleido Workshop Rietreat" },
    { tijd: "18:00", naam: "Dag afsluiting", podium: "Dorpsplein - Aardewerk" },
    { tijd: "18:00", naam: "DeBodhi", podium: "Sloôoase" },
    { tijd: "18:00", naam: "EnkiDoeMaar", podium: "Kaleido Queer Stage" },
    { tijd: "18:00", naam: "Sandhya & Achha", podium: "Kabouterpodium" },
    { tijd: "18:00", naam: "Trackvogels +", podium: "Krater" },
    { tijd: "18:15", naam: "Florelei", podium: "Theo's Theetuin" },
    { tijd: "18:15", naam: "Koen Boeijinga", podium: "Wilgenportaal" },
    { tijd: "18:30", naam: "Concert Wolf heart Sisters", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "18:30", naam: "Pote CompLote - Las Corpa", podium: "Theaterveld" },
    { tijd: "19:00", naam: "Awichas DJ set", podium: "Dorpsplein - Terraspodium Woven Voices" },
    { tijd: "19:00", naam: "Billenschudden met DJ Dragonslayer", podium: "Temple of Self" },
    { tijd: "19:00", naam: "Body paint corner", podium: "De Speeltuin" },
    { tijd: "19:00", naam: "DJ Witte Aap", podium: "Krater" },
    { tijd: "19:00", naam: "Heiko Dijker's Mandala Soul", podium: "Salon" },
    { tijd: "19:00", naam: "Intimate haircuts", podium: "Kaleido Faerie Forest" },
    { tijd: "19:00", naam: "Jolly Mango's", podium: "Area 46" },
    { tijd: "19:00", naam: "Karaoke Bar: Valse Noten", podium: "De Speeltuin" },
    { tijd: "19:00", naam: "TAJ", podium: "Boogie Bos" },
    { tijd: "19:15", naam: "Wild Grace", podium: "Theo's Theetuin" },
    { tijd: "19:30", naam: "DJ Babette", podium: "Kaleido Queer Stage" },
    { tijd: "19:30", naam: "Pup & Cat Play: An Introduction", podium: "Kaleido Workshop Rietreat" },
    { tijd: "19:30", naam: "Toscan's Brew", podium: "Kabouterpodium" },
    { tijd: "20:00", naam: "Cuervo Cuervo", podium: "Krater" },
    { tijd: "20:00", naam: "Divine Kirtan", podium: "Theo's Theetuin" },
    { tijd: "20:00", naam: "Oliv Oliv", podium: "Wilgenportaal" },
    { tijd: "20:30", naam: "Ritmo Revival feat. horns from Mototroko and Zebra streetband", podium: "Dorpsplein - Veld" },
    { tijd: "20:30", naam: "Sharrif Simmons& Grazzhoppa", podium: "Salon" },
    { tijd: "21:00", naam: "Beeldenroute Temple of Self", podium: "Temple of Self" },
    { tijd: "21:00", naam: "DJ Summer", podium: "Kaleido Queer Stage" },
    { tijd: "21:00", naam: "DJ Witte Aap", podium: "Krater" },
    { tijd: "21:00", naam: "De Tranentrekkers", podium: "Rebel Stage" },
    { tijd: "21:00", naam: "Hibotep", podium: "Boogie Bos" },
    { tijd: "21:00", naam: "Kidd Nebula", podium: "Kabouterpodium" },
    { tijd: "21:00", naam: "Leon Row", podium: "Bon Vivant" },
    { tijd: "21:00", naam: "Self-Touch & Sensual Flow", podium: "Kaleido Workshop Rietreat" },
    { tijd: "21:00", naam: "Trippin Jaguar (live)", podium: "Sloôoase" },
    { tijd: "21:30", naam: "XOTO", podium: "Kaleido Queer Stage" },
    { tijd: "22:00", naam: "Anxiety as a Gift", podium: "Kikvors: Metamorphosis" },
    { tijd: "22:00", naam: "DIZZI GEETHA", podium: "Krater" },
    { tijd: "22:00", naam: "Djembefola's", podium: "Dorpsplein - Veld" },
    { tijd: "22:00", naam: "JUNO", podium: "Wilgenportaal" },
    { tijd: "22:00", naam: "Primo Disco", podium: "Area 46" },
    { tijd: "22:00", naam: "Yella Yellabow", podium: "Salon" },
    { tijd: "22:15", naam: "Nightshift", podium: "Salon" },
    { tijd: "22:30", naam: "Velvet Tongues", podium: "Bon Vivant" },
    { tijd: "23:00", naam: "Beeldenroute", podium: "Krater" },
    { tijd: "23:00", naam: "Boogie Movement", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "C19", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "Coen Aerts", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "Collectief in de Lucht", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "Denz de Kroon", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "Dreamweavers", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "Embodied Systems", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "Encounter", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "Floor Nagler", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "Flow Arts", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "Het Spiegelveld", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "Irene van Krimpen", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "Jeroen Cuypers", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "Kaleidomescope", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "Kom uit je schulp", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "Magische Maskerbrigade", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "Mariah Blue", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "Misfit Valley", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "Nadia Innocentia", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "Neon strings", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "Nuki Nibu", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "PUNXIANS", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "Sol Lysergic", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "The Rise, Life and Death of Don Quijote", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "The Shamanic Experience", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "The Wet and Naughty Show", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "Zevende kleur", podium: "Beeldenroute" },
    { tijd: "23:00", naam: "sarangi", podium: "Beeldenroute" },
    { tijd: "23:30", naam: "Carmela Collective", podium: "Boogie Bos" },
    { tijd: "23:30", naam: "Tritha", podium: "Salon" },
    { tijd: "00:00", naam: "DAF - Dutch Acid Family", podium: "DAF/ Rafelrand" },
    { tijd: "00:00", naam: "DJ Captain Spank", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Ellis in Wonderland", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Merlin", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Rump3lst!lsk!", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Snow Whitney", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Vage Paul", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Witte Aap", podium: "Krater" },
    { tijd: "00:00", naam: "Dolle Nina", podium: "Kerk - All Is One" },
    { tijd: "00:00", naam: "Isis & Mozes", podium: "Kerk - All Is One" },
    { tijd: "00:00", naam: "Johansson", podium: "Area 46" },
    { tijd: "00:00", naam: "Julien Chaptal", podium: "Wilgenportaal" },
    { tijd: "00:00", naam: "Leon Row B2B Shimon", podium: "Bon Vivant" },
    { tijd: "00:00", naam: "The Lyrebirds", podium: "Theo's Theetuin" },
    { tijd: "00:00", naam: "Wakhan Project", podium: "Sloôoase" },
    { tijd: "00:00", naam: "Wise Flower", podium: "Rebel Stage" },
    { tijd: "00:30", naam: "DJ RPS Brothers", podium: "De Speeltuin" },
    { tijd: "00:30", naam: "YEKUMI", podium: "Krater" },
    { tijd: "01:00", naam: "Battle for the Sacred Bean by: Bente Kruger & Adhem Kouta", podium: "Bon Vivant" },
    { tijd: "01:00", naam: "Live Music Parlour met Lowfire & Liza Weald", podium: "Temple of Self" },
    { tijd: "01:00", naam: "Prince Pasensi", podium: "Boogie Bos" },
    { tijd: "01:15", naam: "Bradu", podium: "Salon" },
    { tijd: "01:30", naam: "Bring the Joints", podium: "Kabouterpodium" },
    { tijd: "01:30", naam: "Jamsessie met Jarne X Ris", podium: "Rebel Stage" },
    { tijd: "02:00", naam: "Bliz Nochi & Marisa Lia", podium: "Sloôoase" },
    { tijd: "02:00", naam: "Dj Fred Legal Alien", podium: "Area 46" },
    { tijd: "02:00", naam: "Night Drumming", podium: "Dorpsplein - Veld" },
    { tijd: "02:00", naam: "Temple Nacht met Ambient Music & Intential Tea Ceremony (Ocean, Yente & Emmy-K)", podium: "Temple of Self" },
    { tijd: "02:30", naam: "DJ Sucre", podium: "Kabouterpodium" },
    { tijd: "03:00", naam: "Dj Chaakra Legal Alien", podium: "Area 46" },
    { tijd: "03:00", naam: "Edgar Ramiro", podium: "Boogie Bos" },
    { tijd: "03:00", naam: "Inphiknight", podium: "Wilgenportaal" }
  ],

  zo: [
    { tijd: "09:00", naam: "Kinder Kamping", podium: "Camping" },
    { tijd: "11:00", naam: "Morning Yoga - De 5 Elementen Vorm", podium: "Camping" },
    { tijd: "12:00", naam: "Bakfietsband", podium: "Randprogramma" },
    { tijd: "12:00", naam: "Crescone", podium: "Sloôoase" },
    { tijd: "12:00", naam: "DAF - Dutch Acid Family", podium: "DAF/ Rafelrand" },
    { tijd: "12:00", naam: "De VerwonderBus", podium: "Dorpsplein - Veld" },
    { tijd: "12:00", naam: "De zachte landing", podium: "Dorpsplein - Podium Instrumentaal" },
    { tijd: "12:00", naam: "Earth Garden", podium: "Randprogramma" },
    { tijd: "12:00", naam: "Filosofisch kabinet", podium: "Dorpsplein - Veld" },
    { tijd: "12:00", naam: "Le Miracle du Vivant by: Marchal", podium: "Bon Vivant" },
    { tijd: "12:00", naam: "Performances - Sunday", podium: "Bon Vivant" },
    { tijd: "12:00", naam: "Poppenkastvoorstelling", podium: "Randprogramma" },
    { tijd: "12:00", naam: "Woven Voices", podium: "Dorpsplein - Terraspodium Woven Voices" },
    { tijd: "12:15", naam: "Ontwaakceremonie met Sophia Maria Kienhuis en Gilian Baracs", podium: "Krater" },
    { tijd: "12:15", naam: "Sharing Voice / Maxi McNaaughty", podium: "Dorpsplein - Terraspodium Woven Voices" },
    { tijd: "12:30", naam: "Het Beeldjuweel op Zondag", podium: "Kerk - Het Beeldjuweel" },
    { tijd: "12:30", naam: "Kostuums maken voor de optocht", podium: "Dorpsplein - De Wereld in Wording" },
    { tijd: "12:30", naam: "Origin Circle", podium: "Theo's Theetuin" },
    { tijd: "13:00", naam: "4-Hands Massage Arnaud Mooij & Marcel Maurik", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "13:00", naam: "Anja Berkhof & Janfie: klassiek", podium: "Salon" },
    { tijd: "13:00", naam: "Baba Exotica", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "13:00", naam: "Bon Bon Vivant chocolate tasting", podium: "Bon Vivant" },
    { tijd: "13:00", naam: "Bouke en co: Gratis kleding halen & brengen", podium: "Area 46" },
    { tijd: "13:00", naam: "Breathwork ~ Strengthening the Subtle Body", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "13:00", naam: "Conscious Flirting & Heart Led Desire", podium: "Natural High - Tipi" },
    { tijd: "13:00", naam: "Garden of Devotion", podium: "Randprogramma" },
    { tijd: "13:00", naam: "Healing Massage Workshop", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "13:00", naam: "Instrumenten maken voor de optocht", podium: "Dorpsplein - Podium Instrumentaal" },
    { tijd: "13:00", naam: "Lichtconcert met Liza Weald & Pip Robin", podium: "Temple of Self" },
    { tijd: "13:00", naam: "Poi workshop by Bartoz (Bzarr)", podium: "Randprogramma" },
    { tijd: "13:00", naam: "Rasta Robert & Friends", podium: "Natural High - Mama Ger" },
    { tijd: "13:00", naam: "Stray Elf", podium: "Kaleido Queer Stage" },
    { tijd: "13:00", naam: "The Troubadour Car Jamsessie", podium: "Dorpsplein - Podium Instrumentaal" },
    { tijd: "13:00", naam: "Workshop Lino Stempelen", podium: "Dorpsplein - Aardewerk" },
    { tijd: "13:00", naam: "Workshop vuur maken door Robert Bleij", podium: "Dorpsplein - Aardewerk" },
    { tijd: "13:15", naam: "Spoken Word met Smita James en anderen", podium: "Dorpsplein - Terraspodium Woven Voices" },
    { tijd: "13:30", naam: "Morning Yoga - De 5 Elementen Vorm", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "13:30", naam: "Slijm maken", podium: "Kaleido Workshop Rietreat" },
    { tijd: "13:45", naam: "Cedric Vermue", podium: "Salon" },
    { tijd: "14:00", naam: "! RED HET GROENE VELD - TEKEN NU!", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "DJ Witte Aap", podium: "Krater" },
    { tijd: "14:00", naam: "De Drijvende dichter", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "De Spelletjeskast", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "Dougal Hallowes - Sitar Journeys", podium: "Area 46" },
    { tijd: "14:00", naam: "Embrace your No-Talent: Talkshow Time", podium: "Kaleido Queer Stage" },
    { tijd: "14:00", naam: "For Sun", podium: "Boogie Bos" },
    { tijd: "14:00", naam: "Gesamtkunstwerk met Hessel Pijnaker open workshop", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "Hatha Yoga", podium: "Theo's Theetuin" },
    { tijd: "14:00", naam: "Interactief Theater: met de wezens van de Optocht", podium: "Dorpsplein - Veld" },
    { tijd: "14:00", naam: "Kids Show door Jozefien", podium: "Kabouterhuys" },
    { tijd: "14:00", naam: "Kirtan & Mantra Singing Circle", podium: "Temple of Self" },
    { tijd: "14:00", naam: "Photo Booth", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "Pit Hermans", podium: "Vlindertuin" },
    { tijd: "14:00", naam: "Poetry Consults", podium: "Kaleido Faerie Forest" },
    { tijd: "14:00", naam: "Saskia Schmink", podium: "Dorpsplein - Veld" },
    { tijd: "14:00", naam: "Stemvork Healing door Shamatty", podium: "Kabouterhuys" },
    { tijd: "14:00", naam: "WTF Stage", podium: "Wilgenportaal" },
    { tijd: "14:00", naam: "Wij Doen Mee! van stichting Verwonderij", podium: "Beeldenroute" },
    { tijd: "14:00", naam: "Workshop Playfight", podium: "Theaterveld" },
    { tijd: "14:00", naam: "Woven Voices: What's alive in you?", podium: "Dorpsplein - Terraspodium Woven Voices" },
    { tijd: "14:00", naam: "XXL spellen: Schaken, Jenga, Twister", podium: "De Speeltuin" },
    { tijd: "14:30", naam: "Chi Kung met Erik Arty", podium: "Kabouterhuys" },
    { tijd: "14:30", naam: "Reve & Jessy", podium: "Kerk - A' Ma 'Na" },
    { tijd: "15:00", naam: "Avi Adir. Araam Project", podium: "Salon" },
    { tijd: "15:00", naam: "Dapo Star Workshop by The Fire Messiah", podium: "Randprogramma" },
    { tijd: "15:00", naam: "De Grote Voortplantingsshow", podium: "Kaleido Queer Stage" },
    { tijd: "15:00", naam: "Divine Mistress of Craziness", podium: "Randprogramma" },
    { tijd: "15:00", naam: "Festival make-up/makeover met Shotgun Cilla", podium: "Kabouterhuys" },
    { tijd: "15:00", naam: "FreeFlow Flashmob", podium: "Randprogramma" },
    { tijd: "15:00", naam: "Gotcha & Katherina - folkloristische liederen uit Georgië", podium: "Kabouterpodium" },
    { tijd: "15:00", naam: "Het verhaal: met de wezens van de Optocht", podium: "Dorpsplein - Veld" },
    { tijd: "15:00", naam: "Laura Sestri x Rhei", podium: "Sloôoase" },
    { tijd: "15:00", naam: "Mehmet Polat", podium: "Vlindertuin" },
    { tijd: "15:00", naam: "Suricata", podium: "Bon Vivant" },
    { tijd: "15:00", naam: "Tarot & YOU with BHASHA", podium: "Kabouterhuys" },
    { tijd: "15:00", naam: "The Bard's Horn", podium: "Randprogramma" },
    { tijd: "15:00", naam: "Velvet Tongues", podium: "Bon Vivant" },
    { tijd: "15:15", naam: "Embrace your No-Talent by Malle Wally", podium: "Kaleido Queer Stage" },
    { tijd: "15:30", naam: "Kundalini Ceremonie", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "15:30", naam: "Maurício Lobão", podium: "Kerk - A' Ma 'Na" },
    { tijd: "15:30", naam: "Simone Alyssa", podium: "Theo's Theetuin" },
    { tijd: "15:30", naam: "Spirit Songs door Anouk Anansi", podium: "Temple of Self" },
    { tijd: "15:30", naam: "Touch Me", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "15:30", naam: "Wim Hof Methode Ijsbad", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "15:30", naam: "Yin Yoga & Reiki met DjezzManon", podium: "Natural High - Tipi" },
    { tijd: "16:00", naam: "Azuni Raphael", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "16:00", naam: "Bram & Jara", podium: "Vlindertuin" },
    { tijd: "16:00", naam: "De Rebellenklup: Maxi McNaughty & Erwin Mulder", podium: "Kabouterpodium" },
    { tijd: "16:00", naam: "Eric, de Magiër achter het rookgordijn", podium: "Kabouterhuys" },
    { tijd: "16:00", naam: "I dreamt I had hairy teeth - Humo y Polvo", podium: "Theaterveld" },
    { tijd: "16:00", naam: "L'heure Classique", podium: "Wilgenportaal" },
    { tijd: "16:00", naam: "Psychedelic Tea Party", podium: "Area 46" },
    { tijd: "16:00", naam: "The Gritmoaners", podium: "Rebel Stage" },
    { tijd: "16:00", naam: "The Lyrebirds", podium: "Krater" },
    { tijd: "16:00", naam: "Маyapapaya b2b Dragonslayer", podium: "Boogie Bos" },
    { tijd: "16:15", naam: "De vrolijkheid - De kinderoptocht", podium: "Dorpsplein - Veld" },
    { tijd: "16:15", naam: "Flamenco - Todo es de color", podium: "Theo's Theetuin" },
    { tijd: "16:15", naam: "Rae Charmaine", podium: "Salon" },
    { tijd: "16:15", naam: "Wij doen mee! - de kinderoptocht", podium: "Dorpsplein - Veld" },
    { tijd: "16:30", naam: "Angel Tarot", podium: "Kaleido Faerie Forest" },
    { tijd: "16:30", naam: "INOYSON : The Spiritual Journey Beyond Consciousness", podium: "Kerk - A' Ma 'Na" },
    { tijd: "16:30", naam: "Kinderoptocht - verzamelen om", podium: "Dorpsplein - Veld" },
    { tijd: "17:00", naam: "Beeldenroute Kinderen", podium: "Krater" },
    { tijd: "17:00", naam: "Bewegende Lijnen", podium: "Kaleido Workshop Rietreat" },
    { tijd: "17:00", naam: "Double staff Workshop by Bartoz (Bzarr)", podium: "Randprogramma" },
    { tijd: "17:00", naam: "Ecstatic Dance with Richie Lee", podium: "Temple of Self" },
    { tijd: "17:00", naam: "Embrace your No Talent by you?", podium: "Kaleido Queer Stage" },
    { tijd: "17:00", naam: "Red Oak Troubadours", podium: "Vlindertuin" },
    { tijd: "17:00", naam: "Soul Safari", podium: "Sloôoase" },
    { tijd: "17:00", naam: "Workshop Playful Circus Acrobatics", podium: "Theaterveld" },
    { tijd: "17:30", naam: "Dramm, LaBerge & Dramm", podium: "Salon" },
    { tijd: "17:30", naam: "Gong Meditatie", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "17:30", naam: "Healing ragas and mantras", podium: "Theo's Theetuin" },
    { tijd: "17:30", naam: "SoulSong Activation - The Healing Power of Light Language", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "17:30", naam: "Steven de Peven", podium: "Kerk - A' Ma 'Na" },
    { tijd: "17:30", naam: "The Art of Seduction: Een ode aan je vrouw-zijn", podium: "Natural High - Tipi" },
    { tijd: "18:00", naam: "Cairê & Friends - Sacred Prayers", podium: "Krater" },
    { tijd: "18:00", naam: "Coco Coquelicot story telling", podium: "Bon Vivant" },
    { tijd: "18:00", naam: "Cézanne", podium: "Wilgenportaal" },
    { tijd: "18:00", naam: "DJ Try/Me", podium: "Kaleido Queer Stage" },
    { tijd: "18:00", naam: "Dag afsluiting", podium: "Dorpsplein - Aardewerk" },
    { tijd: "18:00", naam: "Headspin", podium: "Kabouterpodium" },
    { tijd: "18:00", naam: "The Cacao Coronation by: Bente Kruger & Adhem Kouta", podium: "Bon Vivant" },
    { tijd: "18:00", naam: "Whats Alive in the room", podium: "Dorpsplein - Terraspodium Woven Voices" },
    { tijd: "18:15", naam: "Katie Bitchcoin", podium: "Boogie Bos" },
    { tijd: "18:30", naam: "I dreamt I had hairy teeth - Humo y Polvo", podium: "Theaterveld" },
    { tijd: "18:30", naam: "Improv-Theater", podium: "Kaleido Workshop Rietreat" },
    { tijd: "18:30", naam: "Shamballa Tribe", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "19:00", naam: "Cuervo Cuervo", podium: "Sloôoase" },
    { tijd: "19:00", naam: "DJ Witte Aap", podium: "Krater" },
    { tijd: "19:00", naam: "Ik Cacao ook van Jou! - Closing Ceremony met live muziek van o.a. Barry Zingt", podium: "Temple of Self" },
    { tijd: "19:00", naam: "Intimate haircuts", podium: "Kaleido Faerie Forest" },
    { tijd: "19:00", naam: "Karaoke Bar: Valse Noten", podium: "De Speeltuin" },
    { tijd: "19:00", naam: "La Prudon x Ibu Ibiza - Hoeden & Modeshow", podium: "Randprogramma" },
    { tijd: "19:00", naam: "MakaAno Stem van de Ziel", podium: "Theo's Theetuin" },
    { tijd: "19:00", naam: "Meraque", podium: "Sloôoase" },
    { tijd: "19:00", naam: "Nita Aartsen Kwartet", podium: "Salon" },
    { tijd: "19:00", naam: "REO MATSUMOTO DJ Set with live Handpan", podium: "Kerk - A' Ma 'Na" },
    { tijd: "19:00", naam: "Solarpunk & Synths", podium: "Area 46" },
    { tijd: "19:00", naam: "Sonny & the Jets", podium: "Rebel Stage" },
    { tijd: "19:00", naam: "Steve Rachmad", podium: "Boogie Bos" },
    { tijd: "19:00", naam: "Verdieping met LEx", podium: "Dorpsplein - Why Not Theater" },
    { tijd: "20:00", naam: "Arp Frique & Family", podium: "Krater" },
    { tijd: "20:00", naam: "DIZZI GEETHA", podium: "Kerk - A' Ma 'Na" },
    { tijd: "20:00", naam: "De Lange Omtrekkende Beweging - Zalf", podium: "Theaterveld" },
    { tijd: "20:00", naam: "Destroying the Last Horcrux", podium: "Kaleido Faerie Forest" },
    { tijd: "20:00", naam: "Landjuweel Temple Space", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "20:00", naam: "MIJNHEER van Ouwenaar", podium: "Salon" },
    { tijd: "20:00", naam: "Mantra Kirtan", podium: "Theo's Theetuin" },
    { tijd: "20:00", naam: "Sunset Sounds: Tjebbe & Jascha", podium: "Kabouterpodium" },
    { tijd: "20:00", naam: "The Maxitaksi", podium: "Kaleido Queer Stage" },
    { tijd: "20:00", naam: "Tribal Organica with DJ Esthetica", podium: "Temple of Self" },
    { tijd: "20:00", naam: "Woodcraft", podium: "Wilgenportaal" },
    { tijd: "20:30", naam: "Latin upbeat freestyle", podium: "Dorpsplein - Veld" },
    { tijd: "21:00", naam: "Anna Babélva: Soft Soirrée Closing", podium: "Bon Vivant" },
    { tijd: "21:00", naam: "DJ Witte Aap", podium: "Krater" },
    { tijd: "21:00", naam: "Fire & Cacao Circle", podium: "Theo's Theetuin" },
    { tijd: "21:00", naam: "House of Chi Live", podium: "Sloôoase" },
    { tijd: "21:00", naam: "Lotte Walda", podium: "Salon" },
    { tijd: "21:00", naam: "Meraki", podium: "Kerk - A' Ma 'Na" },
    { tijd: "21:00", naam: "WRLDBEAT", podium: "Rebel Stage" },
    { tijd: "21:30", naam: "Eli Lux", podium: "Kaleido Queer Stage" },
    { tijd: "21:30", naam: "Relating in the Dark", podium: "Kaleido Workshop Rietreat" },
    { tijd: "21:30", naam: "Wilgendans", podium: "Wilgenportaal" },
    { tijd: "21:45", naam: "Irene van Krimpen", podium: "Kabouterpodium" },
    { tijd: "22:00", naam: "Alex Covert", podium: "Kerk - A' Ma 'Na" },
    { tijd: "22:00", naam: "Boogie Family Closing", podium: "Boogie Bos" },
    { tijd: "22:00", naam: "Bouncen met DJ Laura Jayne", podium: "Temple of Self" },
    { tijd: "22:00", naam: "Celine-Dewy, Jayati & Celestial Roots", podium: "Krater" },
    { tijd: "22:00", naam: "DJ JamieNee", podium: "Area 46" },
    { tijd: "22:00", naam: "DJ Lotta Isopuro", podium: "De Speeltuin" },
    { tijd: "22:00", naam: "Djembefola's", podium: "Dorpsplein - Veld" },
    { tijd: "22:00", naam: "Origins: Krien Jozeph & Merante Tamar & friends", podium: "Kabouterpodium" },
    { tijd: "22:00", naam: "The Rise, Life and Death of Don Quijote", podium: "Kikvors: Metamorphosis" },
    { tijd: "22:30", naam: "Kahmeya", podium: "Kerk - A' Ma 'Na" },
    { tijd: "22:30", naam: "Maringo Berenos", podium: "Salon" },
    { tijd: "23:00", naam: "Anxiety as a Gift", podium: "Kikvors: Metamorphosis" },
    { tijd: "23:00", naam: "GUTEN ABEND", podium: "Kaleido Queer Stage" },
    { tijd: "23:30", naam: "Los Ojos de la Rumba", podium: "Wilgenportaal" },
    { tijd: "00:00", naam: "AMYIR", podium: "Area 46" },
    { tijd: "00:00", naam: "Bon bon Vivant extravaganza", podium: "Kerk - A' Ma 'Na" },
    { tijd: "00:00", naam: "DJ Captain Spank", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Ellis in Wonderland", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Merlin", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Rump3lst!lsk!", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Snow Whitney", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Sucre", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Vage Paul", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "Foelie & Freude (Temple Closing Set)", podium: "Temple of Self" },
    { tijd: "00:00", naam: "Jam olv Joao Vedana", podium: "Salon" },
    { tijd: "00:00", naam: "Jamsessie met Kim Stevenson", podium: "Rebel Stage" },
    { tijd: "00:00", naam: "Meraki", podium: "Krater" },
    { tijd: "00:00", naam: "Purple Flame", podium: "Sloôoase" },
    { tijd: "00:00", naam: "The Grand Procession to the Chocolate Factory", podium: "Bon Vivant" },
    { tijd: "00:30", naam: "Eaglemen", podium: "Wilgenportaal" },
    { tijd: "01:30", naam: "Aggy Lou", podium: "Kerk - A' Ma 'Na" },
    { tijd: "02:00", naam: "Dj Chaakra Legal Alien", podium: "Area 46" },
    { tijd: "02:00", naam: "Ed Noodle", podium: "Sloôoase" },
    { tijd: "02:00", naam: "Mauricio Lobão met Jungle Tribal Dance live set", podium: "Krater" },
    { tijd: "02:00", naam: "Night Drumming", podium: "Dorpsplein - Veld" },
    { tijd: "02:45", naam: "Mona Pirzad", podium: "Kerk - A' Ma 'Na" },
    { tijd: "03:00", naam: "Various DJ's en drums CLOSING", podium: "Krater" }
  ]
};
