/* ========================================================================
   Landjuweel 2026 — het programma per dag.
   Overgenomen uit de officiële Landjuweel-app (versie 15 juli 2026).
   Volgorde binnen een dag maakt niet uit; de app sorteert zelf op tijd.
   Tijden na middernacht (00:00–05:00) horen bij de nacht van die dag.
   ======================================================================== */

var LINEUP = {

  do: [
    { tijd: "12:00", naam: "De VerwonderBus", podium: "Dorpsplein - Veld" },
    { tijd: "12:30", naam: "Origin Circle", podium: "Theo's Theetuin" },
    { tijd: "13:00", naam: "4-Hands Massage Arnaud Mooij & Marcel Maurik", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "14:00", naam: "Bouw mee aan het groeiende insectendorp - Het landschap", podium: "Dorpsplein - De Wereld in Wording" },
    { tijd: "14:00", naam: "Poppenkastvoorstelling", podium: "Randprogramma" },
    { tijd: "14:00", naam: "DAF - Dutch Acid Family", podium: "DAF/ Rafelrand" },
    { tijd: "14:00", naam: "De Spelletjeskast", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "XXL spellen: Schaken, Jenga, Twister", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "Photo Booth", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "Open Mic", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "! RED HET GROENE VELD - TEKEN NU !", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "Bouke en co: Gratis kleding halen & brengen", podium: "Area 46" },
    { tijd: "14:00", naam: "Rochelle Dietz", podium: "Sloôoase" },
    { tijd: "14:00", naam: "Bakfietsband", podium: "Randprogramma" },
    { tijd: "14:00", naam: "Rasta Robert & Friends", podium: "Natural High - Mama Ger" },
    { tijd: "14:00", naam: "Kloek", podium: "Dorpsplein - Veld" },
    { tijd: "14:00", naam: "De Drijvende dichter", podium: "De Speeltuin" },
    { tijd: "14:00", naam: "Lach Workshop", podium: "Area 46" },
    { tijd: "14:00", naam: "Stemvork Healing door Shamatty", podium: "Kabouterhuys" },
    { tijd: "14:00", naam: "Kids Show door Jozefien", podium: "Kabouterhuys" },
    { tijd: "14:30", naam: "Heart Chakra Meditation", podium: "Natural High - Tipi" },
    { tijd: "14:30", naam: "Embodied Dating Club", podium: "Natural High - Kleine Yurt" },
    { tijd: "14:30", naam: "Tender Moments", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "14:30", naam: "Chi Kung met Erik Arty", podium: "Kabouterhuys" },
    { tijd: "14:30", naam: "Self Wellness Practice", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "15:00", naam: "Klei Jezelf Blij Workshop", podium: "Area 46" },
    { tijd: "15:00", naam: "Divine Mistress of Craziness", podium: "Randprogramma" },
    { tijd: "15:00", naam: "HONOUR*REVIVE*SHARE - The Workshop", podium: "Kikvors: Metamorphosis" },
    { tijd: "15:00", naam: "Festival make-upmakeover met Shotgun Cilla", podium: "Kabouterhuys" },
    { tijd: "15:00", naam: "Tarot & YOU with BHASHA", podium: "Kabouterhuys" },
    { tijd: "15:00", naam: "Silk Fans workshop - hosted by Tara Moon", podium: "Randprogramma" },
    { tijd: "15:30", naam: "Ik Cacao van Jou! - Openingsceremonie", podium: "Temple of Self" },
    { tijd: "16:00", naam: "Saskia Schmink", podium: "Dorpsplein - Veld" },
    { tijd: "16:00", naam: "Soep en broodjes", podium: "Dorpsplein - Trommelvuur" },
    { tijd: "16:00", naam: "Verhaal met The Troubadour Car", podium: "Dorpsplein - Podium Instrumentaal" },
    { tijd: "16:00", naam: "Bon Bon Vivant chocolate tasting", podium: "Bon Bon Vivant" },
    { tijd: "16:00", naam: "Algarabía - Bardo Teatro Físico", podium: "Theaterveld" },
    { tijd: "16:00", naam: "Workshop Lino Stempelen", podium: "Dorpsplein - Aardewerk" },
    { tijd: "16:00", naam: "Dromenvangers maken", podium: "Dorpsplein - Aardewerk" },
    { tijd: "16:00", naam: "Opening Festival", podium: "Krater" },
    { tijd: "16:00", naam: "Eric, de Magiër achter het rookgordijn", podium: "Kabouterhuys" },
    { tijd: "16:00", naam: "Het Poppen circus", podium: "Dorpsplein - Why Not Theater" },
    { tijd: "16:30", naam: "Landing Yoga", podium: "Kaleido Workshop Rietreat" },
    { tijd: "17:00", naam: "DJ Elektrolux", podium: "Kabouterpodium" },
    { tijd: "17:00", naam: "Poi workshop by Hidde (Hidden Flow)", podium: "Randprogramma" },
    { tijd: "17:00", naam: "InstrumMensen freestyle rap sessie", podium: "Dorpsplein - Podium Instrumentaal" },
    { tijd: "17:00", naam: "Bouw mee aan het groeiende insectendorp - Het landschap", podium: "Dorpsplein - De Wereld in Wording" },
    { tijd: "17:00", naam: "Wakhan Project", podium: "Sloôoase" },
    { tijd: "17:00", naam: "Ari's Classical Radio Show: Can You Händle It?", podium: "Bon Bon Vivant" },
    { tijd: "17:00", naam: "Taste of Tantra (Authentic Relating) van Tamara Groen", podium: "Temple of Self" },
    { tijd: "17:30", naam: "DIY Ecstatic Bodywork — release & activation", podium: "Natural High - Kleine Yurt" },
    { tijd: "17:30", naam: "Magdalena Rose Codes", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "17:30", naam: "Northern Roots – body, nature & connection", podium: "Natural High - Tipi" },
    { tijd: "17:45", naam: "Wild Grace", podium: "Theo's Theetuin" },
    { tijd: "18:00", naam: "Muziek Tapijt", podium: "Dorpsplein - Podium Instrumentaal" },
    { tijd: "18:00", naam: "Woven Voices Opening met Lex Empress", podium: "Dorpsplein - Terraspodium" },
    { tijd: "18:00", naam: "Flirting for people who are terrible at it", podium: "Kaleido Workshop Rietreat" },
    { tijd: "18:00", naam: "Nevula and the Dragon's Tale", podium: "Krater" },
    { tijd: "18:00", naam: "Gestos", podium: "Salon" },
    { tijd: "18:00", naam: "Organic Sound Group", podium: "Vlindertuin" },
    { tijd: "18:00", naam: "Boogie Family Opening", podium: "Boogie Bos" },
    { tijd: "18:30", naam: "Algarabía - Bardo Teatro Físico", podium: "Theaterveld" },
    { tijd: "18:45", naam: "Heart Songs with Ukulele by Immy Angel", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "19:00", naam: "DJ Witte Aap", podium: "Krater" },
    { tijd: "19:00", naam: "Improvisatie theater", podium: "Natural High - Kleine Yurt" },
    { tijd: "19:00", naam: "Speeddaten", podium: "De Speeltuin" },
    { tijd: "19:00", naam: "Ecstatic Dance with Dj B.ART", podium: "Temple of Self" },
    { tijd: "19:00", naam: "Flamenco - Todo es de color", podium: "Theo's Theetuin" },
    { tijd: "19:00", naam: "Merlijn Nash", podium: "Wilgenportaal" },
    { tijd: "19:00", naam: "Leef vanuit je innerlijke wijsheid", podium: "Natural High - Tipi" },
    { tijd: "19:00", naam: "Breathwork", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "19:00", naam: "Ruigoord Rebels", podium: "Rebel Stage" },
    { tijd: "19:30", naam: "Heiko Dijker's Alien Roots", podium: "Salon" },
    { tijd: "19:30", naam: "Authentiek & verbindend communiceren", podium: "Kaleido Workshop Rietreat" },
    { tijd: "19:30", naam: "Juliska", podium: "Kabouterpodium" },
    { tijd: "19:30", naam: "Music UPLifting Handpan Experience", podium: "Natural High - Buiten podium/ Veld" },
    { tijd: "20:00", naam: "The Elements Fellowship", podium: "Krater" },
    { tijd: "20:00", naam: "Ctd Movement", podium: "Dorpsplein - Terraspodium" },
    { tijd: "20:00", naam: "Purple Flame", podium: "Sloôoase" },
    { tijd: "20:00", naam: "Shimon presents Radio Border: Sunbelt Sounds", podium: "Bon Bon Vivant" },
    { tijd: "20:00", naam: "Trash Skeleton", podium: "Kerk - Punken voor Eigen Parochie" },
    { tijd: "20:00", naam: "Rave Baby - Sandra Kaas", podium: "Theaterveld" },
    { tijd: "20:00", naam: "Yanic", podium: "Boogie Bos" },
    { tijd: "20:00", naam: "Fire & Cacao Circle", podium: "Theo's Theetuin" },
    { tijd: "21:00", naam: "The Bard's Horn", podium: "Randprogramma" },
    { tijd: "21:00", naam: "HAN Here And Now", podium: "Salon" },
    { tijd: "21:00", naam: "The Perculators", podium: "Wilgenportaal" },
    { tijd: "21:00", naam: "DJ Witte Aap", podium: "Krater" },
    { tijd: "21:00", naam: "Kiss My Knoblauch", podium: "Kerk - Punken voor Eigen Parochie" },
    { tijd: "21:00", naam: "Toscan's Brew", podium: "Kabouterpodium" },
    { tijd: "21:00", naam: "Get Painted", podium: "Kaleido Workshop Rietreat" },
    { tijd: "21:00", naam: "Landjuweel Temple Space", podium: "Natural High - Grote Paleis Yurt" },
    { tijd: "21:00", naam: "The Unemployed", podium: "Rebel Stage" },
    { tijd: "21:00", naam: "Victor Sams op Ngoni", podium: "Dorpsplein - Trommelvuur" },
    { tijd: "21:00", naam: "DJ Babette", podium: "Kaleido Queer Stage" },
    { tijd: "21:00", naam: "DJ Steve Kennedy", podium: "De Speeltuin" },
    { tijd: "21:30", naam: "Wormhol DJ", podium: "Boogie Bos" },
    { tijd: "21:30", naam: "DJ FeelofSofie", podium: "Temple of Self" },
    { tijd: "22:00", naam: "The Underbouncers", podium: "Wilgenportaal" },
    { tijd: "22:00", naam: "JPattersson", podium: "Krater" },
    { tijd: "22:00", naam: "The Rise, Life and Death of Don Quijote", podium: "Kikvors: Metamorphosis" },
    { tijd: "22:00", naam: "Mantra Kirtan", podium: "Theo's Theetuin" },
    { tijd: "22:00", naam: "Dj Deun Legal Alien", podium: "Area 46" },
    { tijd: "22:00", naam: "Fooi", podium: "Kerk - Punken voor Eigen Parochie" },
    { tijd: "22:00", naam: "Earth Garden", podium: "Randprogramma" },
    { tijd: "22:00", naam: "Bliz Nochi (live)", podium: "Sloôoase" },
    { tijd: "22:00", naam: "Djembefola's", podium: "Dorpsplein - Trommelvuur" },
    { tijd: "22:30", naam: "SUNN", podium: "Salon" },
    { tijd: "23:00", naam: "Doris Fiore", podium: "Boogie Bos" },
    { tijd: "23:00", naam: "Esta Polyesta", podium: "Krater" },
    { tijd: "23:00", naam: "Duin", podium: "Kikvors: Metamorphosis" },
    { tijd: "23:00", naam: "Bring the Joints", podium: "Kabouterpodium" },
    { tijd: "23:00", naam: "Gente Quente", podium: "Bon Bon Vivant" },
    { tijd: "23:00", naam: "Uitzendbureau", podium: "Kerk - Punken voor Eigen Parochie" },
    { tijd: "23:30", naam: "DJ YΔRL b2b Kahmeya", podium: "Temple of Self" },
    { tijd: "00:00", naam: "DJ Merlin", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "Lowfire", podium: "Salon" },
    { tijd: "00:00", naam: "Jamsessie met the Improvinators", podium: "Rebel Stage" },
    { tijd: "00:00", naam: "Soul Safari", podium: "Sloôoase" },
    { tijd: "00:00", naam: "L.A. Sagne", podium: "Kerk - Punken voor Eigen Parochie" },
    { tijd: "00:00", naam: "DJ Sucre", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Vage Paul", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Snow Whitney", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Rump3lst!lsk!", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "DJ Ellis in Wonderland", podium: "Kabouterhuys" },
    { tijd: "00:00", naam: "Dj Fred Legal Alien", podium: "Area 46" },
    { tijd: "00:00", naam: "Ippy", podium: "Wilgenportaal" },
    { tijd: "00:30", naam: "DJ Captain Spank b2b DJ MacGyver 2.0", podium: "Kabouterpodium" },
    { tijd: "00:30", naam: "DJ JP", podium: "De Speeltuin" },
    { tijd: "00:30", naam: "Abelix", podium: "Boogie Bos" },
    { tijd: "01:00", naam: "Kayva van Gangelen & Piet Jan Blauw", podium: "Krater" },
    { tijd: "01:15", naam: "Zibabu", podium: "Kerk - Punken voor Eigen Parochie" },
    { tijd: "01:30", naam: "Sem Kramer & Cherry", podium: "Salon" },
    { tijd: "02:00", naam: "Kaje Row", podium: "Sloôoase" },
    { tijd: "02:00", naam: "B2B Solame vs FTGRL", podium: "Kerk - Punken voor Eigen Parochie" },
    { tijd: "02:00", naam: "Night Drumming", podium: "Dorpsplein - Trommelvuur" },
    { tijd: "02:00", naam: "Dj Chaakra Legal Alien", podium: "Area 46" },
    { tijd: "02:30", naam: "yak x mari posa", podium: "Boogie Bos" }
  ],

  vr: [],

  za: [],

  zo: []
};
